#!/usr/bin/env bash
# Source-authority gate (the paper's provenance mitigation) on the added writers' paper-route memories: one executor-only run per saved
# writer run (Inkling and DeepSeek V4.1 Flash, three domains, the paper's three seeds), typed incremental, both executors. No writer calls.
# Sources are pooled per run because two runs can share an identical final memory, which the study rejects as overlapping.
set -u
export PATH="$HOME/.local/bin:/c/Users/mikad/.local/bin:$PATH"
cd "$(dirname "$0")"
LOG="${1:-results/driver_$(basename "$0" .sh).log}"
run() {
  local tag; tag=$(printf '%s
' "$@" | awk '/^--tag$/{getline; print; exit}')
  if [ -n "$tag" ] && ls -d results/*/*__"$tag" >/dev/null 2>&1 && grep -lq '"status": "completed"' results/*/*__"$tag"/manifest.json 2>/dev/null; then echo "=== $(date +%H:%M) SKIP (completed run exists) $tag" >> "$LOG"; return 0; fi
  echo "=== $(date +%H:%M) $*" >> "$LOG"; uv run python -m "$@" >> "$LOG" 2>&1 || echo "FAILED: $*" >> "$LOG"
}
echo "=== $(date +%H:%M) PHASE 29e START" >> "$LOG"

run experiments.run --domain cybersecurity --study source_authority --source-run "results/cybersecurity/20260907-020100-204117__authorization-memory-writer__paper-writer-s20260812-cybersecurity-inkling" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260812-cybersecurity-inkling"
run experiments.run --domain cybersecurity --study source_authority --source-run "results/cybersecurity/20260907-030704-632480__authorization-memory-writer__paper-writer-s20260821-cybersecurity-inkling" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260821-cybersecurity-inkling"
run experiments.run --domain cybersecurity --study source_authority --source-run "results/cybersecurity/20260907-040631-133475__authorization-memory-writer__paper-writer-s20260822-cybersecurity-inkling" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260822-cybersecurity-inkling"
run experiments.run --domain cybersecurity --study source_authority --source-run "results/cybersecurity/20260912-192002-963969__authorization-memory-writer__paper-writer-s20260812-cybersecurity-deepseek_v4_1_flash" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260812-cybersecurity-deepseek_v4_1_flash"
run experiments.run --domain cybersecurity --study source_authority --source-run "results/cybersecurity/20260912-203929-027098__authorization-memory-writer__paper-writer-s20260821-cybersecurity-deepseek_v4_1_flash" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260821-cybersecurity-deepseek_v4_1_flash"
run experiments.run --domain cybersecurity --study source_authority --source-run "results/cybersecurity/20260912-220613-370189__authorization-memory-writer__paper-writer-s20260822-cybersecurity-deepseek_v4_1_flash" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260822-cybersecurity-deepseek_v4_1_flash"
run experiments.run --domain finance --study source_authority --source-run "results/finance/20260912-182621-935987__authorization-memory-writer__paper-writer-s20260816-finance-inkling" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260816-finance-inkling"
run experiments.run --domain finance --study source_authority --source-run "results/finance/20260912-182706-038487__authorization-memory-writer__paper-writer-s20260816-finance-deepseek_v4_1_flash" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260816-finance-deepseek_v4_1_flash"
run experiments.run --domain finance --study source_authority --source-run "results/finance/20260912-192850-400540__authorization-memory-writer__paper-writer-s20260821-finance-deepseek_v4_1_flash" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260821-finance-deepseek_v4_1_flash"
run experiments.run --domain finance --study source_authority --source-run "results/finance/20260912-194855-372742__authorization-memory-writer__paper-writer-s20260821-finance-inkling" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260821-finance-inkling"
run experiments.run --domain finance --study source_authority --source-run "results/finance/20260912-201505-785068__authorization-memory-writer__paper-writer-s20260822-finance-deepseek_v4_1_flash" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260822-finance-deepseek_v4_1_flash"
run experiments.run --domain finance --study source_authority --source-run "results/finance/20260912-211450-775567__authorization-memory-writer__paper-writer-s20260822-finance-inkling" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260822-finance-inkling"
run experiments.run --domain procurement --study source_authority --source-run "results/procurement/20260907-005931-906340__authorization-memory-writer__paper-writer-s20260719-procurement-inkling" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260719-procurement-inkling"
run experiments.run --domain procurement --study source_authority --source-run "results/procurement/20260907-014252-803048__authorization-memory-writer__paper-writer-s20260822-procurement-inkling" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260822-procurement-inkling"
run experiments.run --domain procurement --study source_authority --source-run "results/procurement/20260912-182648-422469__authorization-memory-writer__paper-writer-s20260719-procurement-deepseek_v4_1_flash" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260719-procurement-deepseek_v4_1_flash"
run experiments.run --domain procurement --study source_authority --source-run "results/procurement/20260912-191507-202806__authorization-memory-writer__paper-writer-s20260821-procurement-deepseek_v4_1_flash" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260821-procurement-deepseek_v4_1_flash"
run experiments.run --domain procurement --study source_authority --source-run "results/procurement/20260912-195706-729719__authorization-memory-writer__paper-writer-s20260822-procurement-deepseek_v4_1_flash" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260822-procurement-deepseek_v4_1_flash"
run experiments.run --domain procurement --study source_authority --source-run "results/procurement/20260913-040715-719855__authorization-memory-writer__paper-writer-s20260821-procurement-inkling" --writer-strategy incremental --executor-targets gptoss_baseten,deepseek_baseten --batch-size 6 --estimated-cost-usd 6 --tag "gate-s20260821-procurement-inkling"
echo "=== $(date +%H:%M) PHASE 29e DONE" >> "$LOG"
