"""Major rewrite of the extension prose: shorter, story-first, methodology moved to Section 3,
mitigations after the closed loop and writer-side compute. Revised text is wrapped in \\revised{} (green).
Every replacement asserts a single exact match so nothing is silently skipped."""
import pathlib

ICLR = pathlib.Path(r"C:/Users/mikad/Documents/GitHub/eal-bench-iclr")


def sub1(text, old, new, label):
    n = text.count(old)
    assert n == 1, f"{label}: expected 1 match, found {n}\n{old[:200]}"
    return text.replace(old, new)


p = ICLR / "main.tex"
s = p.read_text(encoding="utf-8")

# ------------------------------------------------------------------ macro
s = sub1(s, "\\newcommand{\\added}[1]{{\\color{red}#1}}  % additions under review; remove the color once accepted",
         "\\newcommand{\\added}[1]{{\\color{red}#1}}  % additions under review; remove the color once accepted\n"
         "\\newcommand{\\revised}[1]{{\\color{green!50!black}#1}}  % rewritten in the second pass; remove the color once accepted", "macro")

# ------------------------------------------------------------------ abstract
s = sub1(s, "\\added{The trigger is a later message that repeats a permission the history has since changed: on generated histories that differ only in whether such a restatement occurs, false authority forms after a restatement and almost never without one. An agent that logs its own actions supplies such messages itself, and writing its log back into its history lowers authorized use by 18 points over three rounds. Rebuilding memory from the history instead of patching it removes most of the laundering without the utility cost, and a one-sentence instruction about who may grant authority helps where the failure is a misread message and hurts where it is a rejected write.}",
         "\\revised{The failures trace to one trigger: a later message that repeats a permission the history has since changed. On generated histories that differ only in whether such a restatement occurs, false authority forms after a restatement and almost never without one. Agents that log their own actions supply such messages themselves, and writing the log back into the history erodes authorized use over successive rounds. Rebuilding memory from the history removes most of the laundering while preserving authorized use, and a one-sentence instruction on who may grant authority helps where the writer misreads a message and hurts where its write of a legitimate change is rejected.}", "abstract")

# ------------------------------------------------------------------ introduction
s = sub1(s, "Existing memory evaluations focus on recall, adversarial scenarios, or downstream task performance, leaving the preservation of evolving authorization state comparatively under-measured and motivating a study that separates whether false authority is introduced into memory from whether an executor subsequently acts on it. Figure",
         "\\revised{Existing memory evaluations focus on recall, adversarial scenarios, or downstream task performance, and leave the preservation of evolving authorization state largely unmeasured. We therefore separate whether false authority enters memory from whether an executor later acts on it.} Figure", "intro sentence")
s = sub1(s, "\\added{Measuring the failure is not the same as knowing what causes it, and the two provenance defenses we test show why the distinction matters: both cut laundering, both cost legitimate use, and neither says which message the writer misread. We therefore also ask what the writer reacts to, and the answer, which differs by domain, decides whether a given defense helps, costs utility, or backfires.}",
         "\\revised{Measuring the failure does not explain it. The two provenance defenses we test both reduce laundering and both reject legitimate actions, and neither identifies the message the writer misread. We therefore ask what the writer reacts to. The answer differs by domain, and it determines whether a given defense helps, harms, or trades safety for utility.}", "intro paragraph")
s = sub1(s, "\\item \\added{We locate the trigger and the point of entry. On matched generated histories, false authority forms only after a party without authority restates a superseded permission (0 of 324 unauthorized requests without a restatement, 15.4\\% with two, for GLM 5.2, Kimi K2.6, and Nemotron 3 Ultra). Attributing every failure to the update that introduced it separates procurement and finance, where the writer applies such a restatement, from cybersecurity, where its write of the legitimate change is rejected and the old grant survives.}",
         "\\item \\revised{We locate the trigger and the point of entry. On matched generated histories, false authority forms only after a party without authority restates a superseded permission. Attributing each failure to the memory update that introduced it reveals two distinct writer errors: in procurement and finance the writer applies the restatement, whereas in cybersecurity its write of the legitimate change is rejected and the old grant survives.}", "contribution trigger")
s = sub1(s, "\\item \\added{We show that the agent feeds the channel itself. Written back into its history, the executor's log of escalations and declines is read as evidence about authority, and authorized use falls by 18 points over three rounds against a control with the same updates and neutral content.}",
         "\\item \\revised{We show that the agent feeds this channel itself. When the executor's log of escalations and declines is written back into the history, the writer reads it as evidence about authority, and authorized use falls by 18 points over three rounds relative to a control with identical updates and neutral content.}", "contribution loop")
s = sub1(s, "revealing a safety--utility tradeoff\\added{. Rebuilding memory from the history instead of patching it avoids the tradeoff in every domain, and a one-sentence instruction to the writer removes most of the laundering where the failure is an applied restatement and doubles it where the failure is a rejected write}.",
         "revealing a safety--utility tradeoff\\revised{. Rebuilding memory from the history avoids this tradeoff in every domain, and a one-sentence writer instruction removes most of the laundering where the failure is an applied restatement but doubles it where the failure is a rejected write}.", "contribution mitigations")

# ------------------------------------------------------------------ methods: memory variants described together
s = sub1(s, "relaxing the bound gives no clear improvement (Appendix~\\ref{app:capacity-ablation}), so tight memory limits are not the main cause of the failures.\n",
         "relaxing the bound gives no clear improvement (Appendix~\\ref{app:capacity-ablation}), so tight memory limits are not the main cause of the failures.\n\n"
         "\\revised{Three variants of the typed incremental writer separate the update strategy from the representation and from what the writer can see (Appendix~\\ref{app:rebuild}). A \\textit{hybrid} schema adds one free-text notes field to the typed records. \\textit{Rebuild every three blocks} discards the memory at every third block and rewrites it from the full history, so the incremental writer becomes a periodic one-shot writer. \\textit{Writer-side retrieval} shows the writer, at each update, the six earlier messages most similar to the new block.}\n", "memory variants")
s = sub1(s, "\\added{Three further protocols ask what the writer reacts to. Generated procurement histories come in groups of three that are identical except for the number of later messages, from colleagues or systems without authority, that restate a permission after it was superseded (0, 2, or 4), so within a group the restatements are the only difference (Appendix~\\ref{app:generated-corpus}). A closed loop appends, after each request, one log line stating what the executor did, and the writer updates memory from that line before the next request; a control forked from the same memory receives the same number of updates carrying a content-free notice, so the paired difference isolates the content of the agent's own log (Appendix~\\ref{app:closed-loop}). Every failure in this paper is attributed to the first memory update at which the memory authorizes the request while the ledger does not, found by deterministic replay of the saved memories, and three LLM judges then label what the writer did at that update (Appendix~\\ref{app:diagnosis}).}",
         "\\revised{Three protocols locate the writer's error. \\emph{Generated histories} in procurement come in groups of three that are identical except for the number of later messages (0, 2, or 4) in which a colleague or system restates a permission after it was superseded, so within a group the restatements are the only difference (Appendix~\\ref{app:generated-corpus}). The \\emph{closed loop} appends one log line stating the executor's decision after each request and has the writer update memory from it before the next request; a control forked from the same memory receives the same number of updates with content-free notices, so the paired difference isolates the content of the agent's own log (Appendix~\\ref{app:closed-loop}). \\emph{Attribution} replays every saved memory against the ledger to find the first update at which memory authorizes a request the ledger denies, and three LLM judges then label the writer's error at that update (Appendix~\\ref{app:diagnosis}).}", "protocols paragraph")
s = sub1(s, "\\added{Two further changes act on how the writer writes rather than on what it keeps: rebuilding the typed memory from the full history every three blocks instead of patching it, and prepending one sentence to the writer's instructions, that it record only permissions an authorized approver granted (Appendices~\\ref{app:rebuild} and~\\ref{app:mandate}). These two changes, the closed loop, and the attribution run on GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, and DeepSeek V4.1 Flash; the generated histories are reported for the first three, with Inkling and DeepSeek V4.1 Flash in the appendix. Grok 4.3 and Qwen-Plus did not run these protocols, and every caption names its population.}",
         "\\revised{A third defense changes the writer's instructions rather than its stored output: one sentence, prepended at every update, directs the writer to record only permissions that an authorized approver granted (Appendix~\\ref{app:mandate}). The rebuild variant above serves as a fourth. The writer-side comparisons, the closed loop, and the attribution use five of the seven writers, and every caption names its population.}", "mitigations methods")
s = sub1(s, "GPT-OSS-120B remains the fixed executor\\added{ (Appendix~\\ref{app:writer-ttc-details})}. We separately test",
         "GPT-OSS-120B remains the fixed executor. We separately test", "secondary ref")

# ------------------------------------------------------------------ 4.1
s = sub1(s, "\\added{If incremental writing is the cause, changing the representation should not help and giving the writer the history back should. Both hold (Figure~\\ref{fig:memory-design-across-domains}, last three bars; Appendix~\\ref{app:rebuild}; GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, DeepSeek V4.1 Flash, both executors, three seeds except Inkling's cybersecurity rebuild). A hybrid schema that adds free-text notes to the typed records is still updated from memory alone and still launders, at 12.9\\%, 12.7\\%, and 11.7\\% unauthorized submission in procurement, cybersecurity, and finance, and whether it helps at all depends on the writer. Rebuilding the typed memory from the full history every three blocks, which makes the incremental writer a periodic one-shot writer, cuts unauthorized submission from 25.4\\% to 6.0\\%, from 10.0\\% to 6.0\\% over the 13 writer-seed runs with a rebuild counterpart, and from 31.7\\% to 0.0\\%, with no loss of authorized use. Retrieving the earlier messages most similar to the new block at each update changes nothing, consistent with the misleading material being in the new block itself rather than in what the writer no longer sees.}",
         "\\revised{Two further comparisons confirm that the update strategy, and not the representation, drives the failure (Figure~\\ref{fig:memory-design-across-domains}, last three bars; Appendix~\\ref{app:rebuild}). The hybrid schema still updates from memory alone and still launders, at 12 to 13\\% unauthorized submission in every domain, and whether it improves on typed memory depends on the writer. Rebuilding the memory from the full history every three blocks lowers unauthorized submission to 6\\% or below in every domain with authorized use unchanged or higher, so the incremental writer recovers one-shot behavior as soon as it sees the history again. Writer-side retrieval changes nothing, which places the misleading material in the new block itself rather than in what the writer no longer sees.}", "4.1 paragraph")
s = sub1(s, "for the four memory conditions in each domain\\added{ and, in the last three bars, for three changes to the typed incremental writer: a hybrid schema, rebuilding from the history every three blocks, and the writer instruction of Section~\\ref{sec:mitigation-pareto-results}}.",
         "for the four memory conditions in each domain\\revised{ and, in the last three bars, for the hybrid schema, rebuild every three blocks, and the writer instruction of Section~\\ref{sec:mitigation-pareto-results}}.", "fig2 caption")

# ------------------------------------------------------------------ 4.2
s = sub1(s, "under typed incremental memory, \\added{pooled $P(F)$ is 27.1\\% in procurement, 13.6\\% in cybersecurity, and 51.3\\% in finance, against submission rates of 26.6\\%, 10.5\\%, and 45.9\\%. For Inkling and DeepSeek V4.1 Flash no unauthorized submission occurs on a request the memory does not authorize (0 of 1,106 such trials), which is why the pooled formation rate now exceeds the pooled submission rate where the five original writers' rates were within a point of each other}.",
         "under typed incremental memory, \\revised{pooled $P(F)$ is 27.1\\% in procurement against 26.6\\% unauthorized submission, and the two rates stay within six points of each other in cybersecurity and finance}.", "4.2 formation")
s = sub1(s, "\\added{What the writer reacts to can be isolated on generated procurement histories that are identical within a group except for the number of later messages, from colleagues or systems without authority, that restate a permission after it was superseded (Appendix~\\ref{app:generated-corpus}). With no restatement, false authority never forms (0 of 324 unauthorized requests; GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, GPT-OSS-120B as executor). With two, it forms for 15.4\\% of requests and 16.7\\% are submitted; with four, 10.8\\% and 10.8\\%, not measurably different from two. Attributing every failure in this paper to the update that introduced it shows where this happens (Appendix~\\ref{app:diagnosis}). In procurement and finance three LLM judges label 545 of 549 and 268 of 272 failures as such a restatement applied. In cybersecurity 270 of 303 are instead a rejected update, nearly all at the block carrying the duty officer's signed replacement of the permission list, after which the old grant stays active; in the baseline runs of Appendix~\\ref{app:mandate}, both of the writer's write attempts at that block are rejected as invalid output in 212 of 216 failures. The writer's error therefore differs by domain, and Section~\\ref{sec:mitigation-pareto-results} shows that this decides which defenses work.}",
         "\\revised{The trigger can be isolated on generated procurement histories that differ only in whether a superseded permission is later restated (Appendix~\\ref{app:generated-corpus}). Without a restatement, false authority never forms (0 of 324 unauthorized requests); with two restatements it forms for 15.4\\% of requests, and four restatements are not measurably worse than two. Attribution then shows what the writer does with such a message, and the answer differs by domain (Appendix~\\ref{app:diagnosis}). In procurement and finance nearly every failure is a restatement applied: the writer changes the record to match a message that carried no authority. In cybersecurity nine of ten failures are instead a rejected update at the block carrying the duty officer's signed replacement of the permission list. The writer's plan is correct, but both of its write attempts are rejected as invalid output, and the old grant remains active. Section~\\ref{sec:mitigation-pareto-results} shows that this difference decides which defenses work.}", "4.2 trigger paragraph")

# ------------------------------------------------------------------ 4.3
s = sub1(s, "Cybersecurity is the safest domain for \\added{every writer (Inkling ties it with finance)}, finance the least safe for \\added{all but GLM 5.2 and Inkling}, and Qwen-Plus in finance is the clearest outlier at 43.8\\% baseline. \\added{GLM 5.2 has the highest average authorized use, DeepSeek V4.1 Flash the lowest unauthorized submission, Qwen-Plus the highest, and Inkling the lowest authorized use.} Better writers",
         "Cybersecurity is the safest domain for \\revised{every writer}, finance the least safe for \\revised{most}, and Qwen-Plus in finance is the clearest outlier at 43.8\\% baseline. Better writers", "4.3 rankings")
s = sub1(s, "Once false authority is stored, changing the executor offers little protection, which makes prevention during writing a more promising target than downstream recovery. Thus, upgrading or swapping the executor model does not remediate laundering, and audits and defenses have to target the stored artifact.",
         "\\revised{Once false authority is stored, changing the executor offers little protection; audits and defenses have to target the stored artifact.}", "4.3 transfer sentence")

# ------------------------------------------------------------------ cut the closed-loop section out, rewrite it, and put it before mitigations
cl_start = s.index("\\subsection{\\added{The agent's own log lines are read as changes in authority}}")
cl_end = s.index("\\subsection{Limitations}")
s = s[:cl_start] + s[cl_end:]
closed_loop = r"""\subsection{\revised{The agent's own log is read as a change in authority}}
\label{sec:closed-loop}
\begin{figure}[t]
  \centering
  \includegraphics[width=0.55\linewidth]{figures/closed_loop_control.pdf}
  \caption{\revised{\textbf{Writing the agent's log back into its history lowers authorized use round over round, while unauthorized submission barely moves.} Filled markers: the executor's log line is written back after each request; hollow markers: a control with the same updates and neutral content. GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, and DeepSeek V4.1 Flash, both executors, canonical seed; 95\% bootstrap intervals over chains.}}
  \label{fig:closed-loop}
\end{figure}
\revised{An agent that logs its actions produces the very messages identified above as the trigger, and in deployment those lines enter the history the writer reads. We therefore write the executor's log line for each request back into the history for three rounds and compare against a control with the same updates and neutral content (Appendix~\ref{app:closed-loop}). The writer treats its own log as evidence about authority: it creates 127 permission records that cite nothing but the agent's lines, against 4 in the control, and the judges label nearly all failures entering through a written-back line as an escalation, decline, or order read as a grant. The damage falls on legitimate work. Authorized use at round 3 is 17.6 points below the control (95\% CI $-22.0$ to $-13.3$), with the largest loss in cybersecurity, where the executor escalates most often. Unauthorized submission rises by two points, and finance is unaffected in both arms. A single write-back has no effect; the loss accumulates over rounds (Figure~\ref{fig:closed-loop}).}

\subsection{Writer-side compute shifts the bottleneck to selection}
\label{sec:writer-ttc}

Inference-time compute can change measured model capability \citep{snell2024testtime,cerruti2026safety_eval_ttc,mcfadyen2026inference}, and most failures here form during writing, so we test whether additional writer-side compute reduces them. Each procurement writer samples nested pools of $k\in\{1,2,4,8\}$ candidate memories and selects one using only the visible history, with GPT-OSS-120B fixed as executor (Figure~\ref{fig:writer-ttc}). From $k{=}1$ to $k{=}8$, unauthorized submission falls from 13.2\% to 8.6\% and authorized use rises from 94.2\% to 95.8\%. Generation improves faster than selection: at $k{=}8$ an exact memory exists in 55.0\% of pools, self-review selects one in 26.7\% of them, and an independent DeepSeek reviewer in 30.0\%, which also improves downstream behavior to 7.6\% unauthorized submission and 97.2\% authorized use. In incremental typed memory, final-state error falls from 63.3\% at $k{=}1$ to 51.7\% at $k{=}8$, while observed errors persist in 100\% of cases and self-repair stays at 0\% at every $k$. Added compute avoids errors before they enter memory; the tested reviewers show no ability to remove them afterward. The bottleneck is verification rather than generation, which favors deterministic checks of the kind the mitigations implement over spending further compute on LLM reviewers. Evaluation framing, tested as a secondary check, produces only small and heterogeneous effects on writers and executors (Appendix~\ref{app:evaluation-cue-details}).

"""
mit_start = s.index("\\subsection{Mitigations form a discrete safety--utility Pareto frontier}")
s = s[:mit_start] + closed_loop + s[mit_start:]

# ------------------------------------------------------------------ mitigations
s = sub1(s, "\\added{GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Grok 4.3, and Qwen-Plus, three seeds, both executors. The diamond is the writer instruction of Section~\\ref{sec:mitigation-pareto-results}, pooled over its three domains (GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, DeepSeek V4.1 Flash, three seeds, both executors).}",
         "\\revised{GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Grok 4.3, and Qwen-Plus, three seeds, both executors. The diamond is the writer instruction, pooled over its three domains and five writers (GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, DeepSeek V4.1 Flash).}", "fig3 caption")
old_mit = s[s.index("\\added{Two changes to the writer avoid this cost"):]
old_mit = old_mit[:old_mit.index("}\n\n") + 1]
assert old_mit.endswith("(Appendix~\\ref{app:diagnosis}).}"), old_mit[-80:]
s = sub1(s, old_mit,
         "\\revised{A defense matched to the writer's error avoids this tradeoff (Table~\\ref{tab:writer-side-mitigations}). Rebuilding memory from the history removes the error before it is stored, and it lowers unauthorized submission in every domain with no loss of authorized use (Section~\\ref{sec:memory-design-results}). The writer instruction forbids exactly the error found in procurement and finance, an applied restatement, and there it removes most of the laundering, from 25.4\\% to 5.8\\% and from 31.7\\% to 1.7\\%, with authorized use unchanged or higher and the same direction at every seed. Pooled over domains, it is the one point on the frontier of Figure~\\ref{fig:mitigation-pareto} that keeps authorized use within five points of the baseline. The same sentence doubles unauthorized submission in cybersecurity, where the failure is a rejected write of the legitimate change: an instruction about authority cannot restore a write that never lands, and under it the writer's updates at the critical block fail nearly twice as often. Doubling memory capacity removes the baseline cybersecurity failure, which is therefore a write that does not fit, but leaves most of the instruction's penalty in place, whose rejected writes are malformed rather than oversize (Appendix~\\ref{app:mandate}). Why the instruction degrades the writer's output is not established by these runs. What they establish is that a rule about authority must match the error the writer makes, and that this error can be read from the saved memories before the executor is granted tools (Appendix~\\ref{app:diagnosis}).}", "mitigations paragraph")

# ------------------------------------------------------------------ limitations
s = sub1(s, "\\added{The attribution of each failure to a writer error rests on three LLM judges whose labels no person has checked; a fourth model agreed with the majority label on 46 of 50 blind items, which is not a human check. The rebuild, instruction, closed-loop, and attribution results come from five writers rather than the seven of the main tables, and the generated histories from three. On those histories only the number of restatements is matched; the differences by lifecycle and by gap reported in Appendix~\\ref{app:generated-corpus} are observed across redrawn histories. The capacity test uses one seed and four writers, and it tests whether the cybersecurity failure is a rejected write, not why the instruction makes the write fail.}",
         "\\revised{The attribution rests on three LLM judges whose labels no person has checked; a fourth model agreed with the majority on 46 of 50 blind items, which is a consistency check rather than a human audit. The rebuild, instruction, closed-loop, and attribution results use five of the seven writers, and the generated histories three. On those histories only the number of restatements is matched; the lifecycle and gap differences of Appendix~\\ref{app:generated-corpus} are observed across redrawn histories. The capacity test uses one seed and four writers, and it tests whether the cybersecurity failure is a rejected write, not why the instruction causes one.}", "limitations")

# ------------------------------------------------------------------ conclusion
s = sub1(s, "\\added{The writer's error has a location. On matched histories, false authority forms only after a party without authority restates a permission the history has since changed, and an agent that logs its own actions writes such restatements into its own history. Where the failure is a misread message, as in procurement and finance, a rule about who may grant authority removes most of it at no cost in legitimate use; where it is a rejected write of the legitimate change, as in cybersecurity, the same rule makes it worse. Rebuilding memory from the history removes most of the laundering in every domain without the utility cost the provenance filters pay. A defense therefore has to be chosen against the error the writer makes, and that error can be located in the saved memories before the executor is given tools.}",
         "\\revised{The writer's error has a location and a shape. On matched histories, false authority forms only after a party without authority restates a permission the history has since changed, and an agent that logs its own actions writes such restatements into its own history. Where the writer applies the restatement, as in procurement and finance, a rule about who may grant authority removes most of the laundering with no loss of legitimate use; where its write of the legitimate change is rejected, as in cybersecurity, the same rule makes matters worse. Rebuilding memory from the history removes most of the laundering in every domain and preserves the authorized use that the provenance filters sacrifice. A defense must therefore be chosen against the error the writer makes, and that error can be located in the saved memories before the executor is given tools.}", "conclusion")
s = sub1(s, "leaves a selection bottleneck\\added{ (Appendix~\\ref{app:writer-ttc-details})}. Together",
         "leaves a selection bottleneck. Together", "conclusion ref")

# ------------------------------------------------------------------ appendix: the compute paragraph goes back to the main text
s = sub1(s, "\\subsection{Writer-side inference scaling}\n\\label{app:writer-ttc-details}\n\\label{sec:writer-ttc}\n\n\\paragraph{Writer-side compute shifts the bottleneck to selection.}\n\nInference-time compute can change measured model capability",
         "\\subsection{Writer-side inference scaling details}\n\\label{app:writer-ttc-details}\n\nInference-time compute can change measured model capability", "appendix heading")
para_start = s.index("Inference-time compute can change measured model capability", s.index("\\label{app:writer-ttc-details}"))
para_end = s.index("\n", para_start)
s = s[:para_start] + "Section~\\ref{sec:writer-ttc} summarizes the procurement scaling study; this appendix gives the per-$k$ values." + s[para_end:]

p.write_text(s, encoding="utf-8", newline="\n")
print("rewrite applied")
