"""Pass 3: drop the Limitations section into a future-work paragraph of the conclusion, trim numbers in the
green main text, and shorten every red appendix paragraph (rewritten in green)."""
import pathlib

ICLR = pathlib.Path(r"C:/Users/mikad/Documents/GitHub/eal-bench-iclr")


def sub1(text, old, new, label):
    n = text.count(old)
    assert n == 1, f"{label}: expected 1 match, found {n}\n{old[:200]}"
    return text.replace(old, new)


def replace_par(text, start_marker, new, label):
    """Replace the paragraph that starts with start_marker (a \\added{...} paragraph on one line)."""
    n = text.count(start_marker)
    assert n == 1, f"{label}: start marker found {n} times"
    i = text.index(start_marker)
    j = text.index("}\n", i) + 1
    return text[:i] + new + text[j:]


# ------------------------------------------------------------------ main.tex
p = ICLR / "main.tex"; s = p.read_text(encoding="utf-8")

# Limitations -> future work in the conclusion
i = s.index("\\subsection{Limitations}")
j = s.index("\\section{Conclusion}")
s = s[:i] + s[j:]
s = sub1(s, "Stored permissions deserve the same origin, lifecycle, and audit discipline as entries in an identity and access management system.\n",
         "Stored permissions deserve the same origin, lifecycle, and audit discipline as entries in an identity and access management system.\n\n"
         "\\revised{Future work should target four extensions of this study. The histories retain more structure than real workplace communication so that ground truth stays deterministic, and estimating how prevalent laundering is in deployed systems requires histories drawn from real workflows. Formation is measured deterministically only for typed memory, and validated semantic annotations would extend the false-authority rate to free text. The per-writer, pressure, and closed-loop comparisons rest on one seed each and the writer-side comparisons on five of the seven writers, so replicating them at three seeds across all writers would tighten the estimates. The source-authority gate presumes that authorization-capable principals are known and event sourcing changes the memory architecture, so defenses that locate the writer's error from the saved memories, as Appendix~\\ref{app:diagnosis} does, and act on it without either assumption are the natural next step.}\n", "future work")

# fewer numbers in the green results text
s = sub1(s, "The damage falls on legitimate work rather than on safety: the legitimate action rate at round 3 is 17.6 points below the control (95\\% CI $-22.0$ to $-13.3$), with the largest loss in cybersecurity, where the executor escalates most often, whereas the unauthorized action rate rises by only two points and finance is unaffected in both arms.",
         "The damage falls on legitimate work rather than on safety: the legitimate action rate at round 3 is 17.6 points below the control, with the largest loss in cybersecurity, where the executor escalates most often, whereas the unauthorized action rate barely moves and finance is unaffected in both arms.", "loop numbers")
s = sub1(s, "Pooled over domains, it is the one point on the frontier of Figure~\\ref{fig:mitigation-pareto} that keeps the legitimate action rate within five points of the baseline.",
         "Pooled over domains, it is the point on the frontier of Figure~\\ref{fig:mitigation-pareto} that stays closest to the baseline's legitimate action rate.", "frontier number")

# red appendix paragraphs in main.tex
s = replace_par(s, "\\added{With Inkling and DeepSeek V4.1 Flash run through the same protocol, the gap between generation and selection widens",
                "\\revised{With Inkling and DeepSeek V4.1 Flash run through the same protocol, the gap between generation and selection widens rather than closes: over seven writers a pool of eight contains an exact memory for 54\\% of typed chains against 32\\% at $k{=}1$, while the writer's own selection picks an exact memory for 24\\%. DeepSeek V4.1 Flash shows the pattern most sharply, and Inkling's self-review returns no valid selection in most chains at $k\\geq2$, so its frozen fallback memory is used.}", "ttc red")
s = replace_par(s, "\\added{Inkling and DeepSeek V4.1 Flash were run through the same writer- and executor-stage design",
                "\\revised{Inkling and DeepSeek V4.1 Flash were run through the same writer- and executor-stage design (2,880 paired trials). Every writer-stage contrast has a 95\\% interval that includes zero except two of Inkling's at single seeds, which the other seeds do not repeat, and every executor-stage contrast lies within two points with an interval that includes zero.}", "cue red")
p.write_text(s, encoding="utf-8", newline="\n")

# ------------------------------------------------------------------ extension_results_appendix.tex
p = ICLR / "extension_results_appendix.tex"; s = p.read_text(encoding="utf-8")
s = replace_par(s, "\\added{Inkling and DeepSeek V4.1 Flash were run through the paper's writer route",
                "\\revised{Inkling and DeepSeek V4.1 Flash were run through the paper's writer route, the four memory conditions at three seeds per domain with both executors and the pressure replay, and are pooled into Figure~\\ref{fig:memory-design-across-domains}, Tables~\\ref{tab:memory-design-decomposition}, \\ref{tab:formation-vs-submission}, \\ref{tab:natural-repair}, and~\\ref{tab:writer-domain}, and the seed matrices of Appendix~\\ref{app:three-seed-matrix}. Both reason inside the completion and therefore ran with larger output limits, which no call reached. Table~\\ref{tab:added-writers-route} gives their rates by condition, and both reproduce the pattern of Section~\\ref{sec:memory-design-results}. Neither writer executes an unauthorized request that its final memory does not authorize, so for these two the false-authority rate bounds the unauthorized action rate from above, which is why the seven-writer false-authority rate in Table~\\ref{tab:formation-vs-submission} exceeds the unauthorized action rate in every domain; the gap is widest for DeepSeek V4.1 Flash in finance. The one unauthorized action on oracle-exact memory in Table~\\ref{tab:natural-repair} is a DeepSeek V4.1 Flash procurement pair.}", "added writers")
s = replace_par(s, "\\added{A third executor, GLM 5.3, replayed the frozen memories",
                "\\revised{A third executor, GLM 5.3, replayed the frozen memories of every open-loop study in this appendix, 124 executor-only replays in all, so that three executors answer the same requests against the same memories. On the unauthorized action rate the three are interchangeable, within about one point in every replayed cell, and the writer instruction's paired change is the same to the first decimal for all three. The executors differ only on the legitimate action rate in procurement, where GLM 5.3 executes about 10 points fewer legitimate requests and gains correspondingly more from the instruction. The closed loop is not replayed, because its executor actions are written back and a new executor would produce new chains.}", "third executor")
s = replace_par(s, "\\added{The paper's histories are written by hand, so the features that drive the failure are confounded.",
                "\\revised{The paper's histories are written by hand, so the features that drive the failure are confounded. A generator therefore builds 108 procurement cases in the paper's format from four themes, validated by the same linter as the hand-written corpora, crossing the number of later messages that restate the old permission after it was changed (0, 2, or 4), whether the change amends the grant in place or revokes and replaces it, and the number of blocks between grant and change (1, 2, or 3). The restatements come from colleagues or system status lines, never from the approver. Within a group of three the histories share every turn, the padding, the dates, and the requests, and differ only in the spliced restatements, so the restatement comparison changes one thing at a time, whereas the lifecycle and gap comparisons draw on different base histories and are observational. Runs use typed incremental memory with GPT-OSS-120B as executor, one run per writer, with and without the writer instruction of Appendix~\\ref{app:mandate}.}", "generated design")
s = replace_par(s, "\\added{With everything but the restatements held fixed, GLM 5.2, Kimi K2.6, and Nemotron 3 Ultra form no false permission",
                "\\revised{With everything but the restatements held fixed, GLM 5.2, Kimi K2.6, and Nemotron 3 Ultra form no false permission on any zero-restatement request and form them for 15.4\\% of requests once two restatements follow the change, while four restatements are not measurably different from two (Table~\\ref{tab:restatements}). The legitimate action rate stays at or near 100\\% throughout, so the failure on this corpus is laundering rather than caution. DeepSeek V4.1 Flash matches the three writers exactly at zero restatements, Inkling forms false permissions on 4 of 108 zero-restatement requests, and both added writers fall to zero under the writer instruction, which also cuts the three writers to below 4\\% and nearly triples the number of exact memories.}", "generated results")
s = replace_par(s, "\\added{The same corpus shows two further differences, which are observed rather than matched.",
                "\\revised{The same corpus shows two further differences, which are observed rather than matched: histories that amend the grant in place fail about four times as often as histories that revoke it and issue a replacement, and the failure rate shows no trend across gaps of one to three blocks between grant and change. Because a change of lifecycle or gap also redraws the case's dates, limits, and surrounding text, neither difference is attributed to the lifecycle or the gap alone.}", "observed differences")
s = replace_par(s, "\\added{In the paper the executor's actions vanish, whereas in a deployment they are logged",
                "\\revised{In the paper the executor's actions vanish, whereas in a deployment they are logged and the log becomes part of the history the writer reads. The paper's typed incremental chains at each domain's canonical seed are written once and frozen, and from the same frozen memories two arms are forked and run in lockstep. In the action arm, one workflow-log line built from the executor's tool call and validated decision is appended to the history after each request, the writer updates memory from it, and the next request is answered against the updated memory; in the control arm the appended line is a content-free workspace notice, so the writer performs the same updates on the same schedule. A round is one pass over a case's requests in request-time order, and there are three rounds. Requests are re-dated to follow the log lines they can see whenever that leaves the ledger's verdict unchanged. The difference between arms is paired by chain, with a 95\\% bootstrap interval and a sign-flip permutation test, over GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, and DeepSeek V4.1 Flash with both executors: 30 two-arm runs and 360 chains.}", "loop protocol")
s = replace_par(s, "\\added{Paired over all 360 chains at round 3,",
                "\\revised{Paired over all 360 chains at round 3, the legitimate action rate in the action arm is 17.6 points below the control (95\\% CI $-22.0$ to $-13.3$) and the unauthorized action rate 2.2 points above it (95\\% CI $+0.2$ to $+4.2$). The loss builds over rounds, from 7 points at round 1 to 24 at round 3 for the three original writers, while the paired difference in the unauthorized action rate includes zero at every round; Table~\\ref{tab:closed-loop-writers} gives the per-writer differences, and DeepSeek V4.1 Flash is the one writer whose interval excludes zero. The control also loses legitimate actions in procurement, so part of the decline there is the cost of any repeated update, and only the paired difference isolates the content of the agent's lines.}", "loop paired")
s = replace_par(s, "\\added{The action arm alone shows two effects.",
                "\\revised{The action arm alone shows two effects. First, the writer manufactures permission records out of the agent's own actions: 127 records cite nothing but written-back lines, against 4 in the control, and Appendix~\\ref{app:diagnosis} labels nearly all of them as an escalation, decline, or order read as a grant. Second, real grants disappear: in the cybersecurity action arm the final memories hold 4.5 real, active permission records per chain against 7.8 in the frozen starting memory and 6.5 in the control, and cybersecurity is where the executor refuses most often, escalating or declining at 57\\% of positions against 44\\% in procurement and 32\\% in finance. Which written-back lines cause a real grant to be deactivated has not been traced. In finance neither arm moves either metric, and writing the actions back once, without further rounds, has no effect in any variant, so nothing compounds within one pass. With the writer instruction of Appendix~\\ref{app:mandate}, records created from the agent's own lines fall from 91 to 4 while the round-3 legitimate action rate is unchanged, so the instruction stops the minted records without recovering the loss.}", "two effects")
s = replace_par(s, "\\added{The behavioral rates say how often memory launders authority,",
                "\\revised{The behavioral rates say how often memory launders authority, not which message the writer misread or what it did with it, so attribution proceeds in two stages. First, for every unauthorized request that the final memory authorizes, the saved memory after each block is replayed against the ledger as of that block, and the error block is the first at which memory authorizes the request while the ledger does not and stays so to the end; in the closed loop every permission record whose only cited sources are the agent's own written-back lines is added with the write-back block that created it, and this stage needs no model. Second, three judges (DeepSeek V4 Pro, GLM 5.3, Nemotron 3 Ultra, at temperature 0) each see the policy, the request, the true permission state after the block, the memory before and after, the block's messages, and the writer's plan and patches, and each picks one label from Table~\\ref{tab:labels}; the consensus label is the majority. Memories are followed by lineage, so a failure that enters in the shared history of a two-arm run is counted once, and counts are given both as distinct memory updates and as the requests and records each update affected. The judge Nemotron 3 Ultra is also a writer; its labels differ from the other two mainly in calling a rejected update a misapplied change (Table~\\ref{tab:judges}), and the majority label absorbs that.}", "attribution method")
s = replace_par(s, "\\added{Nearly all 2,250 judged failures fall under three errors,",
                "\\revised{Nearly all 2,250 judged failures fall under three errors, which separate by domain and setting rather than by writer (Table~\\ref{tab:cause}). In the open loop, procurement and finance failures are a restatement applied: a status line, a colleague, or a forwarded copy repeats the superseded figure and the writer changes the record to match. In the closed loop, nearly every failure entering through a written-back block is an escalation, decline, or order read as a grant. Cybersecurity differs in kind, because most of its failures, with or without the instruction, are a rejected update at the block carrying the duty officer's signed replacement of the whole permission list, after which the old permission stays active. The judges agree unanimously on 79\\% of rows, and on a blind sample of fifty failures a fourth model given the judges' inputs agreed with the majority label on 46 (Cohen's $\\kappa=0.88$).}", "three errors")
s = replace_par(s, "\\added{The three errors can each be illustrated by a failure from the runs.",
                "\\revised{The three errors can each be illustrated by a failure from the runs. In a procurement case (GLM 5.2, typed incremental), the ledger's active grant covers compute and storage credits from one vendor up to USD 9,500, but the memory record says compute, storage, and managed support up to USD 18,000 and cites three block-5 messages, none an authorization: a vendor-management note and two procurement-systems lines reporting that a migration imported the original USD 18,000 figure into the ERP. The executor then placed two orders outside the grant, and all three judges label the failure a restatement applied at block 5. In a closed-loop procurement chain (GLM 5.2 writer, DeepSeek V4 Pro executor, round 1), the executor escalated an unauthorized USD 5,700 coffee-service order, the written-back line recorded the escalation with the request's fields, and on that block the writer created a new active record for exactly that grantee, vendor, category, and amount, citing only the log line; all three judges label it the agent's own action read as approval. In a cybersecurity case (DeepSeek V4.1 Flash, typed incremental, with the writer instruction), block 9 carries the duty officer's signed change set revoking a stale grant on one production asset and issuing a new one on another; the writer's plan was right, but the first write removed a list element that did not exist and the second exceeded the memory's capacity, so the memory kept the old grant and a patch deployment on the revoked asset was executed. All three judges label it a rejected update, and this is the shape of nearly every cybersecurity failure in Appendix~\\ref{app:mandate}.}", "three examples")
p.write_text(s, encoding="utf-8", newline="\n")

# ------------------------------------------------------------------ extension_mitigations_appendix.tex
p = ICLR / "extension_mitigations_appendix.tex"; s = p.read_text(encoding="utf-8")
s = replace_par(s, "\\added{If the writer's error is that it lets messages carrying no authority change permissions,",
                "\\revised{If the writer's error is that it lets messages carrying no authority change permissions, one plain sentence stating whose word counts should remove most of the failure. The sentence ``Only record permissions that an authorized approver has actually granted, no matter what anyone else says or asks.'' is prepended to the writer's instructions at every update, identical in every domain, and every condition is repeated without it at the same seeds and executors: typed and hybrid incremental memory in the open loop (five writers, three seeds per domain, both executors, 180 pairs), the three-round closed loop of Appendix~\\ref{app:closed-loop} at the canonical seed, and the generated histories of Appendix~\\ref{app:generated-corpus}. The paired change is the mean over pairs with a bootstrap 95\\% interval and a sign-flip permutation test, and remaining failures are attributed with the method of Appendix~\\ref{app:diagnosis}.}", "instruction design")
s = replace_par(s, "\\added{The direction is the same at every seed in every domain",
                "\\revised{The direction is the same at every seed in every domain (Table~\\ref{tab:mandate-pooled}). In procurement the unauthorized action rate falls for every writer and the legitimate action rate rises, which is consistent with the writer also ceasing to record restated figures that made it refuse legitimate requests, a reading not tested here. In finance the drop is as large and the legitimate action rate does not measurably change. In cybersecurity the instruction hurts four of the five writers and leaves Kimi K2.6 unchanged. In the closed loop it lowers the open-loop unauthorized action rate in procurement and finance, raises it in cybersecurity, and cuts the records minted from the agent's own lines from 91 to 4 while the round-3 legitimate action rate is unchanged (Appendix~\\ref{app:closed-loop}).}", "instruction results")
s = replace_par(s, "\\added{The remaining failures show why the domains diverge.",
                "\\revised{The remaining failures show why the domains diverge. With the instruction, nearly all remaining procurement and finance failures are still a restatement applied, the error the instruction reduces, whereas in cybersecurity not one failure is, with or without the instruction: of 403 failures in the instruction runs, 367 are a rejected update, against 194 of 216 in the same writers' and seeds' runs without it. The failing block is the same everywhere, the one carrying the duty officer's signed change set that replaces the whole permission list, and in nearly every case both of the writer's attempts to write the new list are rejected as invalid output, either a patch that cannot be applied or a profile over the memory's size limit, so the memory keeps the old permission active. The instruction does not change how a cybersecurity failure looks but nearly doubles how often one happens, and the attempt logs show the rejected writes rather than what the writer took the change set's authority to be.}", "remaining failures")
s = replace_par(s, "\\added{A capacity test asks whether the cybersecurity failure is a write that cannot fit.",
                "\\revised{A capacity test asks whether the cybersecurity failure is a write that cannot fit. At the canonical seed with typed incremental memory, both executors, and the four writers whose four arms all completed, capacity is either the calibrated 2,646 tokens or twice that (Table~\\ref{tab:capacity}). Doubling capacity removes most of the baseline failure, with the unauthorized action rate falling from 12.5\\% to 1.6\\% and no chain having both writes rejected at the change-set block. With the instruction, doubling capacity helps less and the instruction's own penalty persists at 8.2\\%, where none of the remaining rejections is for size and all are patches that cannot be applied or malformed calls. The baseline cybersecurity failure is therefore a write that does not fit, and the instruction adds a second failure, a write that does not parse, which capacity does not reach.}", "capacity")
s = replace_par(s, "\\added{We compare three designs with the paper's typed incremental memory",
                "\\revised{We compare three designs with the paper's typed incremental memory on the same runs, writers, executors, and requests, so that only the design varies. The hybrid schema adds one free-text notes field to the typed records, with everything the ledger checks kept in the records and formation scored on the records only; rebuilding every three blocks starts the writer from an empty memory at every third block and has it rewrite the memory from the history so far, patching as usual in between; writer-side retrieval shows the writer, at each update, the new block plus the six earlier messages most similar to it by keyword search. Table~\\ref{tab:writer-side-mitigations} pools GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, and DeepSeek V4.1 Flash with both executors at three seeds per domain, except that Inkling's rebuild in cybersecurity is at the canonical seed only, because its other two seeds repeatedly exceeded the run's time limit.}", "designs")
s = replace_par(s, "\\added{Rebuilding lowers the unauthorized action rate for every writer in every domain",
                "\\revised{Rebuilding lowers the unauthorized action rate for every writer in every domain and raises the legitimate action rate (Table~\\ref{tab:writer-side-mitigations}), and it is the one design change that holds across writers. The hybrid schema depends on the writer: it helps the three original writers in procurement and DeepSeek V4.1 Flash everywhere, but for Inkling in cybersecurity the unauthorized action rate rises from 18.8\\% to 62.5\\% in one cell. Retrieval changes no cell for any memory type, which is consistent with the misleading material being in the new block the writer already reads rather than in what it has forgotten. Free text launders less than typed memory under incremental writing but gives up legitimate actions, because about half its updates exceed the size limit and are discarded.}", "designs results")
s = replace_par(s, "\\added{When a rebuild lands matters,",
                "\\revised{When a rebuild lands matters, because in the paper's procurement cases nearly all formation comes from the six-block cases. On those cases a rebuild at the last block leaves a 2.5\\% unauthorized action rate, a rebuild at block 4 followed by two patches leaves 48.1\\%, and never rebuilding leaves 38.0\\% (one seed; GLM 5.2, Kimi K2.6, Nemotron 3 Ultra). The laundering happens in the last two blocks, where the superseded permission is restated, so a rebuild helps only when it comes after those messages, which a deployment cannot time in advance, and each rebuild reads the whole history, so its cost grows with the history. The three-block period reported here is one point on an unmeasured curve rather than an optimum.}", "rebuild timing")
s = replace_par(s, "\\added{Section~\\ref{sec:mitigation-pareto-results} pools the source-authority gate and bounded event sourcing",
                "\\revised{Section~\\ref{sec:mitigation-pareto-results} pools the source-authority gate and bounded event sourcing over GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Grok 4.3, and Qwen-Plus, whereas Inkling and DeepSeek V4.1 Flash were run afterwards and are reported separately, because event sourcing fails for Inkling for a reason unrelated to the design. The gate is applied to the two writers' saved typed incremental memories at three seeds per domain, keeping a record only if every source it cites is a message from a principal allowed to grant authorization, and both executors then answer the same requests from the original and the gated memory. Event sourcing runs the event writer at the paper's 4,096-token completion budget against the writer's own saved incremental typed memory from the same seed.}", "origin intro")
s = replace_par(s, "\\added{The gate reproduces Table~\\ref{tab:source-authority-aligned-domain} on the two writers",
                "\\revised{The gate reproduces Table~\\ref{tab:source-authority-aligned-domain} on the two writers (Table~\\ref{tab:added-gate}): it removes most of the unauthorized action rate in procurement and all of it in finance at the cost of most legitimate actions, and changes nothing in cybersecurity, where no record cites a source the gate would reject. Event sourcing lowers the unauthorized action rate for both writers in procurement with the legitimate action rate unchanged, and for DeepSeek V4.1 Flash in cybersecurity and finance (Table~\\ref{tab:added-event}). Inkling's event arm collapses on the longer cybersecurity and finance histories because Inkling reasons inside the completion and 262 of its 1,552 event-writer calls hit the 4,096-token budget, so 658 event updates are rejected and its event-sourced memory falls behind the history. That is a limit of the protocol's budget rather than of the design, and the two writers are not pooled with each other or with the paper's five.}", "origin results")
p.write_text(s, encoding="utf-8", newline="\n")
print("pass 3 applied")
