"""Prose pass on the method paragraphs of the extension appendices: plainer academic prose, no lists of which
models ran which protocol, and no restated caveats. Result paragraphs are rewritten separately once the parity
runs are in (apply_parity.py)."""
import pathlib

ICLR = pathlib.Path(r"C:/Users/mikad/Documents/GitHub/eal-bench-iclr")


def replace_par(text, start_marker, new, label):
    n = text.count(start_marker)
    assert n == 1, f"{label}: start marker found {n} times"
    i = text.index(start_marker); j = text.index("}\n", i) + 1
    return text[:i] + new + text[j:]


p = ICLR / "extension_results_appendix.tex"; s = p.read_text(encoding="utf-8")
s = replace_par(s, "\\revised{The paper's histories are written by hand, so the features that drive the failure are confounded.",
                "\\updated{Because the benchmark histories are written by hand, the features that might drive the failure are confounded with one another. We therefore generate 108 procurement cases in the benchmark's format from four themes, validated by the same linter as the hand-written corpora, and cross three factors: the number of later messages that restate the old permission after it has been changed (0, 2, or 4), whether the change amends the grant in place or revokes it and issues a replacement, and the number of blocks between the grant and the change (1, 2, or 3). Restatements come from colleagues or from system status lines, never from the approver. Within a group of three histories that share a theme, lifecycle, and gap, every turn, every date, and every request is identical, and only the spliced restatements differ, so the restatement comparison changes one thing at a time. The lifecycle and gap comparisons draw on different base histories and are observational. Each writer runs once on the corpus with typed incremental memory and GPT-OSS-120B as executor, with and without the writer instruction of Appendix~\\ref{app:mandate}.}", "gen design")
s = replace_par(s, "\\revised{In the paper the executor's actions vanish, whereas in a deployment they are logged",
                "\\updated{In the open-loop protocol the executor's actions leave no trace, whereas a deployed agent logs them, and the log becomes part of the history its memory writer reads. The closed loop tests what the writer does with those lines. The typed incremental chains at each domain's canonical seed are written once and frozen, and two arms are forked from the same frozen memories and run in lockstep. In the action arm, one workflow-log line built from the executor's tool call and validated decision is appended to the history after each request, the writer updates memory from it, and the next request is answered against the updated memory. In the control arm the appended line is a content-free workspace notice, so the writer performs the same updates on the same schedule without any action content. A round is one pass over a case's requests in request-time order, and the loop runs for three rounds. Requests are re-dated to follow the log lines they can see whenever that leaves the ledger's verdict unchanged. The difference between arms is paired by chain, with a 95\\% bootstrap interval over chains and a sign-flip permutation test; each writer runs with both executors.}", "loop protocol")
s = replace_par(s, "\\revised{The behavioral rates say how often memory launders authority, not which message the writer misread or what it did with it, so attribution proceeds in two stages.",
                "\\updated{The behavioral rates measure how often memory launders authority but not which message the writer misread or what it did with it, so we attribute every failure in two stages. In the first, mechanical stage, the saved memory after each block is replayed against the ledger as of that block for every unauthorized request that the final memory authorizes, and the error block is the first at which memory authorizes the request while the ledger does not and remains so to the end; in the closed loop, every permission record whose only cited sources are the agent's own written-back lines is added together with the write-back block that created it. In the second stage, three judges (DeepSeek V4 Pro, GLM 5.3, and Nemotron 3 Ultra at temperature 0) each see the policy, the request, the true permission state after the block, the memory before and after, the block's messages, and the writer's plan and patches, and each assigns one of the labels in Table~\\ref{tab:labels}; the consensus label is the majority. Memories are followed by lineage, so a failure that enters in the shared history of a two-arm run is counted once, and counts are reported both as distinct memory updates and as the requests and records each update affected. Nemotron 3 Ultra is also a writer and labels failures of its own updates; its labels differ from the other two mainly in calling a rejected update a misapplied change (Table~\\ref{tab:judges}), which the majority label absorbs.}", "attribution method")
p.write_text(s, encoding="utf-8", newline="\n")

p = ICLR / "extension_mitigations_appendix.tex"; s = p.read_text(encoding="utf-8")
s = replace_par(s, "\\revised{If the writer's error is that it lets messages carrying no authority change permissions,",
                "\\updated{If the writer's error is to let messages that carry no authority change stored permissions, then a plain statement of whose word counts should remove most of the failure, and where it does not, the failure needs something other than a rule. The sentence ``Only record permissions that an authorized approver has actually granted, no matter what anyone else says or asks.'' is prepended to the writer's instructions at every update, identically in every domain, and every condition is repeated without it at the same seeds and with the same executors: typed and hybrid incremental memory in the open loop at three seeds per domain, the three-round closed loop at the canonical seed, and the generated histories. The paired change is the mean over writer, seed, executor, and memory cells of the rate with the instruction minus the rate without it, with a bootstrap 95\\% interval and a sign-flip permutation test, and the remaining failures are attributed with the method of Appendix~\\ref{app:diagnosis}.}", "instruction design")
s = replace_par(s, "\\revised{We compare three designs with the paper's typed incremental memory on the same runs, writers, executors, and requests, so that only the design varies.",
                "\\updated{We compare three designs with typed incremental memory on the same runs, writers, executors, and requests, so that only the design varies. The hybrid schema adds one free-text notes field to the typed records; everything the ledger checks stays in the records, notes hold anything else, such as pending or informal changes, and formation is scored on the records alone. Rebuilding every three blocks starts the writer from an empty memory at every third block and has it rewrite the memory from the history so far, while between rebuilds it patches as usual. Writer-side retrieval shows the writer, at each update, the new block together with the six earlier messages most similar to it by keyword search, while the executor still sees only the memory. Table~\\ref{tab:writer-side-mitigations} pools all writers with both executors at three seeds per domain.}", "designs")
p.write_text(s, encoding="utf-8", newline="\n")
print("method prose applied")
