"""Rewrite the red (added) passages of the ICLR main text: shorter, findings first, no coined labels."""
from pathlib import Path

ICLR = Path(r"C:/Users/mikad/Documents/GitHub/eal-bench-iclr")
p = ICLR / "main.tex"
s = p.read_text(encoding="utf-8")


def sub1(text, old, new, label):
    n = text.count(old)
    assert n == 1, f"{label}: expected 1 match, found {n}\n{old[:160]}"
    return text.replace(old, new)


# Abstract
s = sub1(s, "\\added{In a deployment that logs its actions, the agent's own escalation and decline records feed back into memory as changes in authority, and authorized use falls by 18 points over three rounds.}",
         "\\added{When the agent's own action log is written back into its history, the writer reads escalations and declines as changes in authority, and authorized use falls by 18 points over three rounds.}", "abstract")

# Contributions
s = sub1(s, "\\item \\added{We show that the agent's own logged actions feed the failure: when the executor's escalations and declines are written back into the history, the writer treats them as changes in authority and deactivates real permissions, lowering authorized use by 18 points over three rounds against a matched control.}",
         "\\item \\added{We show that the agent's own log feeds the failure: written back into the history, the executor's escalations and declines are read as changes in authority, and authorized use falls by 18 points over three rounds against a matched control.}", "contribution 5")

# Section 3.2 mitigations
s = sub1(s, "\\added{Two interventions act on the writer instead: rebuilding memory from the full history every three blocks rather than patching it, and prepending one sentence to the writer's instructions that only permissions granted by an authorized approver may be recorded. These interventions, the generated histories of Section~\\ref{sec:mechanism-results}, and the closed loop of Section~\\ref{sec:closed-loop} use five writers, GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, and DeepSeek V4.1 Flash; Appendices~\\ref{app:generated-corpus} to~\\ref{app:rebuild} give the protocols.}",
         "\\added{Two further interventions change the writer rather than the memory: rebuilding the memory from the full history every three blocks instead of patching it, and an instruction to record only permissions that an authorized approver granted. They run on five writers (GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, DeepSeek V4.1 Flash), as do the generated histories of Section~\\ref{sec:mechanism-results} and the closed loop of Section~\\ref{sec:closed-loop}; Appendices~\\ref{app:generated-corpus} to~\\ref{app:rebuild} give the protocols.}", "3.2 mitigations")

# Section 4.1 memory designs
s = sub1(s, "\\added{The ordering holds across memory designs (Appendix~\\ref{app:rebuild}). A hybrid schema that adds free-text notes to the typed records lowers unauthorized submission in procurement and finance and raises it in cybersecurity; retrieving earlier messages at update time changes nothing; and rebuilding the memory from the full history every three blocks instead of patching it lowers unauthorized submission for every writer in every domain, to 6.0\\% in procurement, 6.0\\% in cybersecurity, and 0.0\\% in finance, with authorized use unchanged or higher.}",
         "\\added{Two other memory designs behave the same way (Appendix~\\ref{app:rebuild}). A hybrid schema that adds free-text notes to the typed records is still updated incrementally and still launders: it lowers unauthorized submission in procurement and finance and raises it in cybersecurity. Rebuilding the typed memory from the full history every three blocks, which turns the incremental writer into a periodic one-shot writer, lowers unauthorized submission from 25.4\\% to 6.0\\% in procurement, 10.4\\% to 6.0\\% in cybersecurity, and 31.7\\% to 0.0\\% in finance with no loss of authorized use, for GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, and DeepSeek V4.1 Flash. Retrieving earlier messages at update time changes nothing.}", "4.1 designs")

# Section 4.2 generated histories
s = sub1(s, "\\added{Which message the writer acts on can be isolated with generated procurement histories that are identical except for the number of later restatements of a superseded permission by parties without authority (Appendix~\\ref{app:generated-corpus}). With no restatement, no false authority forms (0 of 324 unauthorized requests for GLM 5.2, Kimi K2.6, and Nemotron 3 Ultra); with two, it forms for 15.4\\% and 16.7\\% are submitted; with four, 10.8\\%. The writer responds to the restatement, not to the change. Additional writer-side compute lowers unauthorized submission from 13.2\\% to 8.6\\% at eight candidate memories but never repairs an error once stored (Appendix~\\ref{app:writer-ttc-details}).}",
         "\\added{What the writer reacts to can be isolated with generated procurement histories that differ only in how many later messages from parties without authority restate a superseded permission (Appendix~\\ref{app:generated-corpus}). With no restatement, false authority never forms (0 of 324 unauthorized requests for GLM 5.2, Kimi K2.6, and Nemotron 3 Ultra); with two restatements it forms for 15.4\\% of requests and 16.7\\% are submitted; with four, 10.8\\% and 10.8\\%. The writer applies the restatement, not the change that preceded it. More writer-side compute lowers unauthorized submission from 13.2\\% to 8.6\\% at eight candidate memories but never repairs an error once it is stored (Appendix~\\ref{app:writer-ttc-details}).}", "4.2 generated")

# Section 4.4 writer-side interventions
s = sub1(s, "\\added{Interventions on the writer itself avoid this cost when they match the writer's error (Table~\\ref{tab:writer-side-mitigations}). Rebuilding memory from the history every three blocks lowers unauthorized submission in every domain with no loss of authorized use. A one-line instruction to record only permissions granted by an authorized approver cuts unauthorized submission from 25.4\\% to 5.8\\% in procurement and from 31.7\\% to 1.7\\% in finance at no cost in authorized use, but raises it from 10.4\\% to 21.8\\% in cybersecurity. The judged failures explain the split (Appendix~\\ref{app:diagnosis}): in procurement and finance the writer applies restatements from parties without authority, which the instruction addresses; in cybersecurity it fails to write the duty officer's change set, and the instruction makes those rejected writes twice as frequent.}",
         "\\added{Changing the writer avoids this cost when the change matches the writer's error (Table~\\ref{tab:writer-side-mitigations}). Rebuilding memory from the history every three blocks lowers unauthorized submission in every domain with no loss of authorized use (Section~\\ref{sec:memory-design-results}). Instructing the writer to record only permissions granted by an authorized approver cuts unauthorized submission from 25.4\\% to 5.8\\% in procurement and from 31.7\\% to 1.7\\% in finance with authorized use unchanged, but raises it from 10.4\\% to 21.8\\% in cybersecurity. The judged failures explain the split (Appendix~\\ref{app:diagnosis}): in procurement and finance the writer applies restatements from parties without authority, which the instruction forbids; in cybersecurity the writer fails to record the duty officer's change set, and with the instruction those failed writes nearly double.}", "4.4 writer")

# Section 4.5 closed loop
s = sub1(s, "\\added{When the executor's log line for each request is written back into the history for three rounds (Appendix~\\ref{app:closed-loop}), the writer treats it as evidence. Against a control with the same number of updates and neutral content, authorized use at round 3 is 17.6 points lower (95\\% CI $-22.0$ to $-13.3$) and 30 points lower in cybersecurity, while unauthorized submission changes little ($+2.2$ points, 95\\% CI $+0.2$ to $+4.2$; Figure~\\ref{fig:closed-loop}). The writer creates permission records that cite nothing but the agent's own lines (127, against 4 in the control) and deactivates real grants when a line reports an escalation or a decline, so the loss is largest where the executor refuses most: at 60\\% of positions in cybersecurity, 43\\% in procurement, and 34\\% in finance, where neither metric moves. The agent's record of its own caution is read as a change in authority, and the cost is legitimate work.}",
         "\\added{When the executor's log line for each request is written back into the history for three rounds (Appendix~\\ref{app:closed-loop}), the writer reads it as evidence about authority. Against a control that receives the same number of updates with neutral content, authorized use at round 3 is 17.6 points lower (95\\% CI $-22.0$ to $-13.3$), and 30 points lower in cybersecurity, while unauthorized submission barely moves ($+2.2$ points, 95\\% CI $+0.2$ to $+4.2$; Figure~\\ref{fig:closed-loop}). The writer deactivates real grants when a line reports an escalation or a decline, and creates 127 permission records that cite nothing but the agent's own lines, against 4 in the control. The loss follows the executor's refusal rate: 60\\% of positions in cybersecurity, 43\\% in procurement, and 34\\% in finance, where neither metric moves.}", "4.5 closed loop")

s = sub1(s, "\\caption{\\added{Writing the executor's actions back into the history: authorized use (top) and unauthorized submission (bottom) over three rounds, against a control with the same number of updates and neutral content.}}",
         "\\caption{\\added{\\textbf{Writing the executor's actions back into the history lowers authorized use.} Authorized use (top) and unauthorized submission (bottom) over three rounds, against a control with the same number of updates and neutral content.}}", "closed-loop caption")

p.write_text(s, encoding="utf-8", newline="\n")
for bad in ("one-line instruction", "One-line instruction", "Baseten", "canonical seed", "paired chains", "of the seven writers", "five of seven", "extension stud"):
    assert bad not in s, bad
print("prose applied; added passages:", s.count("\\added{"))
