"""Build the reviewer's main.tex from the current one: every replacement below is a red passage (or one of the three
documented black-text exceptions). Then install the two new appendix files."""
import pathlib
import shutil

ICLR = pathlib.Path(r"C:/Users/mikad/Documents/GitHub/eal-bench-iclr")
NEW = pathlib.Path(r"C:/Users/mikad/.claude/jobs/e03609a8/tmp/seven/new")
p = ICLR / "main.tex"; s = p.read_text(encoding="utf-8")
shutil.copy(p, NEW / "main.before.tex")


def sub1(text, old, new, label):
    n = text.count(old)
    assert n == 1, f"{label}: expected 1 match, found {n}\n{old[:200]}"
    return text.replace(old, new)


def span(text, start, end, new, label):
    i = text.find(start); assert i >= 0 and text.count(start) == 1, f"{label}: start not unique/found"
    j = text.find(end, i); assert j >= 0, f"{label}: end not found"
    j += len(end)
    return text[:i] + new + text[j:]


# ---- abstract
s = sub1(s, "\\added{When the agent's own action log is written back into its history, the writer reads escalations and declines as changes in authority, and authorized use falls by 18 points over three rounds.}",
         "\\added{The trigger is a later message that repeats a permission the history has since changed: on generated histories that differ only in whether such a restatement occurs, false authority forms after a restatement and almost never without one. An agent that logs its own actions supplies such messages itself, and writing its log back into its history lowers authorized use by 18 points over three rounds. Rebuilding memory from the history instead of patching it removes most of the laundering without the utility cost, and a one-sentence instruction about who may grant authority helps where the failure is a misread message and hurts where it is a rejected write.}", "abstract")

# ---- intro paragraph
s = sub1(s, "converts directly into a purchase, a system change, or a trade.\n\n% The same evaluation protocol",
         "converts directly into a purchase, a system change, or a trade.\n\n\\added{Measuring the failure is not the same as knowing what causes it, and the two provenance defenses we test show why the distinction matters: both cut laundering, both cost legitimate use, and neither says which message the writer misread. We therefore also ask what the writer reacts to. Generated histories that vary one feature at a time locate the trigger in later messages that restate a superseded permission. Attributing each failure to the memory update that introduced it shows that the writer's error differs by domain. A closed loop in which the agent's own log is written back into its history shows that the agent supplies such messages itself. Which error a deployment faces decides whether a given defense helps, costs utility, or backfires.}\n\n% The same evaluation protocol", "intro paragraph")

# ---- contributions
old_bullets = ("\\item We evaluate mitigation strategies and show that reducing authorization laundering can come at the cost of undergranting legitimate authority, revealing a safety--utility tradeoff\\added{; rebuilding memory from the history instead of patching it reduces laundering without that cost}.\n"
               "\\item \\added{We show that the agent's own log feeds the failure: written back into the history, the executor's escalations and declines are read as changes in authority, and authorized use falls by 18 points over three rounds against a matched control.}\n")
new_bullets = ("\\item \\added{We locate the trigger and the point of entry. On matched generated histories, false authority forms only after a party without authority restates a superseded permission (0 of 324 unauthorized requests without a restatement, 15.4\\% with two, for GLM 5.2, Kimi K2.6, and Nemotron 3 Ultra). Attributing every failure to the update that introduced it separates procurement and finance, where the writer applies such a restatement, from cybersecurity, where its write of the legitimate change is rejected and the old grant survives.}\n\n"
               "\\item \\added{We show that the agent feeds the channel itself. Written back into its history, the executor's log of escalations and declines is read as evidence about authority, and authorized use falls by 18 points over three rounds against a control with the same updates and neutral content.}\n \n"
               "\\item We evaluate mitigation strategies and show that reducing authorization laundering can come at the cost of undergranting legitimate authority, revealing a safety--utility tradeoff\\added{. Rebuilding memory from the history instead of patching it avoids the tradeoff in every domain, and a one-sentence instruction to the writer removes most of the laundering where the failure is an applied restatement and doubles it where the failure is a rejected write}.\n")
s = sub1(s, old_bullets, new_bullets, "contributions")

# ---- 3.2 protocols paragraph
s = sub1(s, "Appendix~\\ref{app:pressure-prompts} gives the exact treatments and replay invariants.\n\n\\paragraph{Mitigations.}",
         "Appendix~\\ref{app:pressure-prompts} gives the exact treatments and replay invariants.\n\n\\added{Three further protocols ask what the writer reacts to. Generated procurement histories come in groups of three that are identical except for the number of later messages, from colleagues or systems without authority, that restate a permission after it was superseded (0, 2, or 4), so within a group the restatements are the only difference (Appendix~\\ref{app:generated-corpus}). A closed loop appends, after each request, one log line stating what the executor did, and the writer updates memory from that line before the next request; a control forked from the same memory receives the same number of updates carrying a content-free notice, so the paired difference isolates the content of the agent's own log (Appendix~\\ref{app:closed-loop}). Every failure in this paper is attributed to the first memory update at which the memory authorizes the request while the ledger does not, found by deterministic replay of the saved memories, and three LLM judges then label what the writer did at that update (Appendix~\\ref{app:diagnosis}).}\n\n\\paragraph{Mitigations.}", "3.2 protocols")

# ---- 3.2 mitigations sentence
s = span(s, "\\added{Two further interventions change how the writer writes", "give the protocols.}",
         "\\added{Two further changes act on how the writer writes rather than on what it keeps: rebuilding the typed memory from the full history every three blocks instead of patching it, and prepending one sentence to the writer's instructions, that it record only permissions an authorized approver granted (Appendices~\\ref{app:rebuild} and~\\ref{app:mandate}). These two changes, the closed loop, and the attribution run on GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, and DeepSeek V4.1 Flash; the generated histories are reported for the first three, with Inkling and DeepSeek V4.1 Flash in the appendix. Grok 4.3 and Qwen-Plus did not run these protocols, and every caption names its population.}", "3.2 mitigations")

# ---- models and estimation
s = sub1(s, "and DeepSeek V4.1 Flash \\citep{deepseekai2026deepseekv41flash}}.", "and DeepSeek V4.1 Flash \\citep{deepseekai2026deepseekv41flash} (Appendix~\\ref{app:added-writers})}.", "models appendix ref")
s = sub1(s, "run with 32,768- and 16,384-token limits}.", "run with 32,768- and 16,384-token limits, which no call reached}.", "no call reached")
s = sub1(s, "and intervals are pointwise and unadjusted for multiplicity.\n",
         "and intervals are pointwise and unadjusted for multiplicity. \\added{The closed-loop and writer-instruction comparisons are paired by chain and by writer, seed, and executor cell respectively, with 95\\% bootstrap intervals over the pairs and a sign-flip permutation test; the generated-history comparison is matched within groups and reports Wilson intervals.}\n", "estimation")

# ---- 4.1
s = span(s, "\\added{If this explanation is right", "it changes nothing.}",
         "\\added{If incremental writing is the cause, changing the representation should not help and giving the writer the history back should. Both hold (Appendix~\\ref{app:rebuild}; GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, DeepSeek V4.1 Flash, three seeds, both executors). A hybrid schema that adds free-text notes to the typed records is still updated from memory alone and still launders, at 12.9\\%, 12.7\\%, and 11.7\\% unauthorized submission in procurement, cybersecurity, and finance, and whether it helps at all depends on the writer. Rebuilding the typed memory from the full history every three blocks, which makes the incremental writer a periodic one-shot writer, cuts unauthorized submission from 25.4\\% to 6.0\\%, from 10.4\\% to 6.0\\%, and from 31.7\\% to 0.0\\% with no loss of authorized use. Retrieving the earlier messages most similar to the new block at each update changes nothing, consistent with the misleading material being in the new block itself rather than in what the writer no longer sees.}", "4.1")

# ---- 4.2
s = sub1(s, "\\added{pooled $P(F)$ is 27.1\\% in procurement, 13.6\\% in cybersecurity, and 51.3\\% in finance, against submission rates of 26.6\\%, 10.5\\%, and 45.9\\%}.",
         "\\added{pooled $P(F)$ is 27.1\\% in procurement, 13.6\\% in cybersecurity, and 51.3\\% in finance, against submission rates of 26.6\\%, 10.5\\%, and 45.9\\%. No unauthorized submission occurs on a request the memory does not authorize, so formation is an upper bound on submission, and the gap is requests the executor escalated or declined despite the memory.}", "4.2 formation")
s = span(s, "\\added{What the writer reacts to can be isolated", "(Appendix~\\ref{app:writer-ttc-details}).}",
         "\\added{What the writer reacts to can be isolated on generated procurement histories that are identical within a group except for the number of later messages, from colleagues or systems without authority, that restate a permission after it was superseded (Appendix~\\ref{app:generated-corpus}). With no restatement, false authority never forms (0 of 324 unauthorized requests; GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, GPT-OSS-120B as executor). With two, it forms for 15.4\\% of requests and 16.7\\% are submitted; with four, 10.8\\% and 10.8\\%, not measurably different from two. The writer records the restatement in place of the change that preceded it. Attributing every failure in this paper to the update that introduced it shows where this happens (Appendix~\\ref{app:diagnosis}). In procurement and finance three LLM judges label 545 of 549 and 268 of 272 failures as such a restatement applied. In cybersecurity 270 of 303 are instead a rejected update at the block carrying the duty officer's signed replacement of the permission list, after which the old grant stays active; in the baseline runs of Appendix~\\ref{app:mandate}, both of the writer's write attempts at that block are rejected as invalid output in 212 of 216 failures. The writer's error therefore differs by domain, and Section~\\ref{sec:mitigation-pareto-results} shows that this decides which defenses work. Additional writer-side compute avoids some errors before they are stored but repairs none afterwards (Appendix~\\ref{app:writer-ttc-details}).}", "4.2 generated")

# ---- 4.4
s = sub1(s, "The circle is the typed-incremental baseline, and the squares are the two mitigations.}\n  \\label{fig:mitigation-pareto}",
         "The circle is the typed-incremental baseline, and the squares are the two mitigations. \\added{GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Grok 4.3, and Qwen-Plus, three seeds, both executors.}}\n  \\label{fig:mitigation-pareto}", "pareto caption")
s = sub1(s, "respectively. No configuration dominates another on the pooled estimates", "respectively. \\added{Among these three,} no configuration dominates another on the pooled estimates", "among these three")
s = span(s, "\\added{Two changes to the writer avoid this cost", "error the writer actually makes.}",
         "\\added{Two changes to the writer avoid this cost, one everywhere and one only where it matches the writer's error (Table~\\ref{tab:writer-side-mitigations}; GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, DeepSeek V4.1 Flash, three seeds, both executors). Rebuilding memory from the history every three blocks lowers unauthorized submission in every domain with no loss of authorized use (Section~\\ref{sec:memory-design-results}). The one-sentence instruction to record only permissions an authorized approver granted cuts unauthorized submission from 25.4\\% to 5.8\\% in procurement and from 31.7\\% to 1.7\\% in finance, in the same direction at every seed and with authorized use unchanged or higher, and raises it from 10.4\\% to 21.8\\% in cybersecurity while lowering authorized use by 10 points. The split follows the attribution of Section~\\ref{sec:mechanism-results}. The instruction forbids what the procurement and finance failures are, a restatement applied, and cannot reach the cybersecurity failure, a write of the legitimate change that is never stored. Under the instruction, failures at that block nearly double (216 to 403 over the same writers and seeds) and in 376 of the 403 both write attempts are rejected as invalid output. Doubling the memory capacity removes the baseline cybersecurity failure (12.5\\% to 1.6\\%; GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, DeepSeek V4.1 Flash, canonical seed) and shrinks the instruction's penalty without removing it (8.2\\% with the instruction at double capacity, where the rejected writes are malformed patches rather than oversize profiles). Why the instruction makes a write fail is not established by these runs. What they do establish is that a rule about authority has to be matched to the error the writer makes, and that the block where the error enters can be found from the saved memories alone (Appendix~\\ref{app:diagnosis}).}", "4.4")

# ---- 4.5
s = sub1(s, "\\subsection{\\added{Writing the agent's own actions back into the history lowers authorized use}}", "\\subsection{\\added{The agent's own log lines are read as changes in authority}}", "4.5 heading")
s = sub1(s, "\\caption{\\added{\\textbf{Writing the executor's actions back into the history lowers authorized use.} Authorized use (top) and unauthorized submission (bottom) over three rounds, against a control with the same number of updates and neutral content.}}",
         "\\caption{\\added{\\textbf{Writing the agent's log back into its history lowers authorized use round over round, while unauthorized submission barely moves.} Filled markers: the executor's log line is written back after each request; hollow markers: a control with the same updates and neutral content; GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, and DeepSeek V4.1 Flash, both executors, canonical seed, 95\\% bootstrap intervals over chains.}}", "4.5 caption")
s = span(s, "\\added{When the executor's log line for each request", "where neither metric moves.}",
         "\\added{An agent that logs its actions produces the kind of message Section~\\ref{sec:mechanism-results} identifies as the trigger, and in a deployment those lines enter the history the writer reads. When the executor's log line for each request is written back for three rounds (Appendix~\\ref{app:closed-loop}; GLM 5.2, Kimi K2.6, Nemotron 3 Ultra, Inkling, DeepSeek V4.1 Flash, both executors, 360 paired chains), the writer treats it as evidence about authority. It creates 127 permission records that cite nothing but the agent's own lines, against 4 in the control, and the judges label 186 of the 192 failures that enter through a written-back line as the agent's own escalation, decline, or order read as a grant. The behavioral cost is to utility. Authorized use at round 3 is 17.6 points below the control (95\\% CI $-22.0$ to $-13.3$) and 30 points below in cybersecurity, the domain where the executor escalates most often and where the final memories hold fewer real active permissions than the control; which lines cause a real grant to be deactivated is not established. Unauthorized submission rises by 2.2 points (95\\% CI $+0.2$ to $+4.2$), small and at the edge of detection, and in finance neither metric moves in either arm. Writing the actions back once, with no further rounds, has no effect; the loss builds over rounds (Figure~\\ref{fig:closed-loop}). An agent that logs its own actions into the history its memory writer reads therefore loses legitimate authority round over round, and Section~\\ref{sec:mitigation-pareto-results}'s instruction stops the minted records without recovering that loss.}", "4.5 paragraph")

# ---- limitations, conclusion
s = sub1(s, "\\added{The failure labels in Appendix~\\ref{app:diagnosis} come from three LLM judges and have not been checked by a person.}",
         "\\added{The attribution of each failure to a writer error rests on three LLM judges whose labels no person has checked; a fourth model agreed with the majority label on 46 of 50 blind items, which is not a human check. The rebuild, instruction, closed-loop, and attribution results come from five writers rather than the seven of the main tables, and the generated histories from three. On those histories only the number of restatements is matched; the differences by lifecycle and by gap reported in Appendix~\\ref{app:generated-corpus} are observed across redrawn histories. The capacity test uses one seed and four writers, and it tests whether the cybersecurity failure is a rejected write, not why the instruction makes the write fail.}", "limitations")
s = span(s, "\\added{False authority forms when a later message repeats", "which error the writer makes.}",
         "\\added{The writer's error has a location. On matched histories, false authority forms only after a party without authority restates a permission the history has since changed, and an agent that logs its own actions writes such restatements into its own history. Where the failure is a misread message, as in procurement and finance, a rule about who may grant authority removes most of it at no cost in legitimate use; where it is a rejected write of the legitimate change, as in cybersecurity, the same rule makes it worse. Rebuilding memory from the history removes most of the laundering in every domain without the utility cost the provenance filters pay. A defense therefore has to be chosen against the error the writer makes, and that error can be located in the saved memories before the executor is given tools.}", "conclusion")

# ---- guide
s = sub1(s, "\\added{, the generated histories, the closed loop, and the failure labels}", "\\added{, the two added writers and a third executor, the generated histories, the closed loop, and the attribution of every failure to the writer's error}", "guide 2")
s = sub1(s, "\\added{, the writer instruction, the memory designs, and the provenance mitigations on Inkling and DeepSeek V4.1 Flash}", "\\added{, the writer instruction and the capacity test, the memory designs, and the provenance mitigations on Inkling and DeepSeek V4.1 Flash}", "guide 3")

# ---- compute-scaling appendix (documented black-text exception 2)
s = sub1(s, "\\subsection{Writer-side inference scaling details}\n\\added{[Moved from the main text.]}\n\n\\paragraph{Writer-side compute shifts the bottleneck to selection.}\n\\label{sec:writer-ttc}\n",
         "\\subsection{Writer-side inference scaling}\n\\label{app:writer-ttc-details}\n\\label{sec:writer-ttc}\n\n\\paragraph{Writer-side compute shifts the bottleneck to selection.}\n", "ttc heading")
s = sub1(s, " Full trajectories and protocol details appear in Appendix~\\ref{app:writer-ttc-details}.", "", "ttc self reference")
s = sub1(s, "\\end{figure}\n\n\n\\label{app:writer-ttc-details}\n\nThe procurement scaling study", "\\end{figure}\n\nThe procurement scaling study", "ttc label move")
s = sub1(s, "rather than repairing errors after they enter persistent memory.\n\n\\input{multiseed_appendix.tex}",
         "rather than repairing errors after they enter persistent memory.\n\n\\added{With Inkling and DeepSeek V4.1 Flash run through the same protocol, the gap between generation and selection widens rather than closes: over seven writers a pool of eight contains an exact memory for 54\\% of 168 typed chains against 32\\% at $k{=}1$, while the writer's own selection picks an exact memory for 24\\% against 32\\% and agrees with the oracle's choice 43\\% of the time against 76\\% at $k{=}2$. DeepSeek V4.1 Flash shows the pattern most sharply (an exact memory available in 42\\% then 71\\% of pools, selected in 42\\% then 21\\%). Inkling's pools improve little (25\\% to 33\\%) and its self-review returns no valid selection in 83 to 100\\% of chains at $k\\geq2$, so its frozen fallback memory is used.}\n\n\\input{multiseed_appendix.tex}", "ttc seven-writer paragraph")

# ---- eval-cue appendix: the reviewer added one red paragraph after the executor-side paragraph
s = sub1(s, "but they also do not reveal a large shared response that could explain the main memory-mediated effect.\n",
         "but they also do not reveal a large shared response that could explain the main memory-mediated effect.\n\n\\added{Inkling and DeepSeek V4.1 Flash were run through the same writer- and executor-stage design (2,880 paired trials, 144 paired typed memories). Every writer-stage contrast on unauthorized submission and authorized use has a 95\\% interval that includes zero, except two of Inkling's at single seeds (drops of 6.5 and 9.3 points in unauthorized submission under the generic cue, not repeated at the other seeds); executor-stage contrasts are within two points with intervals including zero.}\n", "eval cue paragraph")

p.write_text(s, encoding="utf-8", newline="\n")
shutil.copy(NEW / "extension_results_appendix.tex", ICLR / "extension_results_appendix.tex")
shutil.copy(NEW / "extension_mitigations_appendix.tex", ICLR / "extension_mitigations_appendix.tex")
print("installed")
