"""Tightens docs/extension_studies.md to what the runs support: the generated-corpus lifecycle and gap comparisons are
described as observed (only the stale levels are matched), the mandate's cybersecurity mechanism is provisional, the
Section 6 tables count distinct memory updates alongside affected requests and records, the claim table says what a
stronger statement would need, and the human check of the judge labels is prepared. Final-state wording only.
Run from the eal-bench root after scratch/section6_v2.py has been run into /tmp/s6.md (path below)."""
import pathlib
import sys

DOC = pathlib.Path("docs/extension_studies.md")
S6 = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else None
s = DOC.read_text(encoding="utf-8").replace("\r\n", "\n")


def rep(old: str, new: str) -> None:
    global s
    assert s.count(old) == 1, (s.count(old), old[:100])
    s = s.replace(old, new, 1)


# ---- status
rep("## Status, 2026-09-13", "## Status, 2026-09-14")
rep("Every table is from the final runs; every failure in those runs was judged with the Section 6 method.",
    "Every table is from the final runs; every failure in those runs was judged with the Section 6 method. The judge labels have not been checked by a person; a blind sample for that check is prepared (open item 1).")

# ---- proposed results section
rep("2. **The trigger is a restatement of a superseded permission.** New, from Section 4. The matched generated corpus: zero restatements form nothing (0 of 324), two form 15%, four add nothing; amendments launder four times more than revoke-and-replace; the gap between grant and change does not matter. One table (three rows by stale count, two by lifecycle). This is the paper's first statement about *which histories* fail, and it explains the incremental result: a writer that never revisits earlier blocks reads each restatement as news.",
    "2. **The trigger is a restatement of a superseded permission.** New, from Section 4. The generated corpus, where the stale-restatement comparison is matched (the three levels share every other turn): zero restatements form nothing (0 of 324), two form 15%, four form 11%, not measurably different from two. Two further differences on the same corpus are observed, not matched: histories that amend a grant in place fail more often than histories that revoke and replace it (17% against 4.5%), and the failure rate shows no trend across gaps of one to three blocks. One table (three rows by stale count, two by lifecycle, the latter marked as observational). This is the paper's first statement about *which histories* fail, and it fits the incremental result: a writer that never revisits earlier blocks reads each restatement as news.")
rep("in cybersecurity the writer fails to write the one large legitimate change and keeps the old permission. One table (cause by setting). This reframes cybersecurity, which the paper currently presents as the \"safest\" domain: it fails differently, not less, and the paper's own observation that gating does nothing there follows from it.",
    "in cybersecurity the writer's update at the block carrying the one large legitimate change is rejected and the old permission stays. One table (cause by setting, counting distinct memory updates as well as affected requests and records). This reframes cybersecurity, which the paper currently presents as the \"safest\" domain: its failures are of a different kind, and the paper's own observation that gating does nothing there is consistent with that. The labels are the judges' until the human check (open item 1) is done, and the text says so.")
rep("and the one-line mandate (near-zero utility cost in procurement and finance, minted records 91 → 4, harmful in cybersecurity where the failure is an unapplied update). One figure with a domain facet, and cybersecurity as the illustration: a rule about authority cannot fix an update that was never written.",
    "and the one-line mandate (no measured utility cost in procurement and finance, minted records 91 → 4, harmful in cybersecurity, where the judged failures are rejected updates). One figure with a domain facet, and cybersecurity as the illustration that the same line helps in two domains and hurts in the third. The explanation, that a rule about authority does not reach a failure where the update is never written, is the reading the labels suggest and is stated as provisional.")

# ---- what does not go in: GLM 5.3 is an open decision
rep("- *GLM 5.3 as a writer*: ran two studies only; adds nothing the seven writers do not show. Not in the paper. As an executor it is the third column of every open-loop table (Section 5), and belongs in the executor-agreement sentence of the generality subsection.",
    "- *GLM 5.3*: it ran as a writer in two studies (paper route, memory grid) and as a third executor on every open-loop study (Section 5). Whether the paper reports it as a writer, as an executor, or not at all is an open decision (open item 5); it should not appear as both.")

# ---- open items
rep("1. **Human validation of the judge labels.** Subsections 3 and 5 rest on three LLM judges. A stratified sample of fifty rows (by label and domain), read by a person against the block and the memory diff, is the check. Until it is done the mechanism claims are the judges' labels, and the text must say so.",
    "1. **Human check of the judge labels.** Subsections 3 and 5 rest on three LLM judges, and the proposed explanation of the mandate's cybersecurity reversal rests on the `update failed` label in particular. A blind sample of fifty judged failures, stratified by majority label and domain, is prepared in `results/diagnosis/human_check/`: `sheet.md` shows for each item exactly what the judges saw and nothing of what they said, `labels.csv` is the template to fill in, and `scratch/human_check_score.py` reports agreement with the majority label and Cohen's kappa against `key.csv`. Until it is read, the mechanism claims are the judges' labels, and the text says so.")
rep("4. **Wording discipline.** Every statement in subsections 2 to 5 carries its count and interval, the null on unauthorized submission stays a null, and mechanisms are the judges' labels until item 1 is done.",
    "4. **Wording discipline.** Every statement in subsections 2 to 5 carries its count and interval; the null on unauthorized submission stays a null and is stated as not detected, never as no effect; comparisons that are not matched (lifecycle, gap) are described as observed differences; and mechanisms are the judges' labels until item 1 is done.\n5. **GLM 5.3's role.** It is a writer in two studies and an executor in every open-loop study. Decide whether the paper reports it as a writer (two studies), as the third executor (with the closed loop, the pressure route and the paper's five writers' paper route stated as two-executor), or leaves it out.")

# ---- claim table: add what a stronger claim would need
rep("**How far each claim is supported.** Strength is judged by design (paired or controlled), size, and seeds; \"single seed\" means the canonical seed of each domain.",
    "**How far each claim is supported.** Strength is judged by design (paired or controlled), size, and seeds; \"single seed\" means the canonical seed of each domain. The last column says what evidence a stronger statement would need.")
i = s.index("| Claim | Evidence | Strength | How it is stated |")
j = s.index("**Open checks before the paper.**")
s = s[:i] + """| Claim | Evidence | Strength | How it is stated | What a stronger claim would need |
|---|---|---|---|---|
| Incremental writing launders; rebuilding removes most of it (S1) | 5 writers × 2 executors (3 with GLM 5.3); procurement 3 seeds, cybersecurity and finance 1 seed; 648 and 192–384 unauthorized requests per row | strong in procurement, moderate elsewhere | as measured, per domain | rebuild at the other two seeds in cybersecurity and finance (ten runs) |
| The hybrid schema helps (S1) | same runs; contradicted for Inkling on cybersecurity (1 seed) | writer-dependent | "lowers unauthorized submission for the paper's writers; not general" | more seeds for the added writers on the grid; the data support a per-writer statement only |
| Rebuild timing matters (S2) | procurement, 1 seed, six-block cases only | weak | observation; a curve is deferred | a curve of rebuild period against unauthorized submission and writer cost, at three seeds |
| Action write-back mints records and cuts authorized use (S3) | 18 two-arm runs, 216 paired chains (30 runs, 360 chains with the added writers), sign-flip permutation p<0.001; records 93 vs 1 | strong | as measured | nothing further for the pooled statement; the other two seeds for a per-domain one |
| Action write-back raises unauthorized submission (S3) | same runs: +2.9 points, interval −0.0 to +5.8 (five writers: +2.2, interval +0.2 to +4.2) | not detected, or small | stated as not detected at this size, with the interval; never as no effect | about four times the chains for a ±1.5-point interval, or more rounds, since the point estimate grows with round |
| Restatements are the trigger (S4) | 108 matched groups, 3 writers (+2 added), GPT-OSS (+GLM 5.3); the three stale levels share every other turn; 324 requests per level | strong for 0 vs 2; 2 vs 4 not distinguished (10.8% vs 15.4%, intervals overlap) | as measured; "four not measurably different from two", never "four add nothing" | more stale levels and a larger corpus to bound the 2-vs-4 difference |
| Amendments launder more than revoke-and-replace; the gap does not matter (S4) | same corpus, but a case with a different lifecycle or gap is drawn from a different base history (dates, caps, filler, theme), and only revoke-and-replace has implicit variants | observational: the difference could come from the redrawn text | described as an observed difference with no cause given; "no trend at one to three blocks", never "no effect" | histories matched across lifecycle and gap the way the stale levels are: the same base draw with only the change wording, or only the block distance, varied |
| Added writers reproduce the paper (S5) | paper route: 3 seeds per domain, both executors; grid: procurement 3 seeds, others 1 | strong on the paper route, moderate on the grid | as measured; single-seed cells marked by their n | nothing further for the paper route; more seeds on the grid |
| A third executor acts on the same memories the same way (S5, third executor) | 124 executor-only replays with GLM 5.3: memory grid, generated corpus, mandate at 3 seeds, added writers' paper route; same frozen memories as the two-executor runs | strong for unauthorized submission, which tracks the other executors cell by cell; authorized use is lower for GLM 5.3 in procurement | as measured; closed loop, pressure route and the paper's five writers' paper route stated as two-executor | the 45 paper-route replays once those run directories are available; new closed-loop chains for a third executor there |
| Flash's closed loop raises unauthorized submission (S5) | 72 chains, +3.9, interval +1.6 to +6.6 | moderate (one writer, one seed) | as measured, not generalized | the other two seeds for Flash |
| Three causes by setting and domain (S6) | 2,250 judged rows from 874 distinct memory updates, three LLM judges, 79% unanimous | strong as a description of the judges' labels | labels are the judges'; counts given as updates and as affected requests and records | the human check (open item 1); disagreement with the majority label on more than a few of the fifty items would mean relabeling |
| The mandate lowers unauthorized submission in procurement and finance and raises it in cybersecurity (S7) | open loop: 5 writers × 2 executors × 3 seeds per domain, 180 paired cells, sign-flip p < 0.001 in procurement, finance (typed) and cybersecurity, same direction at every seed; closed loop at the canonical seed | strong | as measured | nothing further for the open loop; the closed loop at the other two seeds if that comparison goes in |
| Why the mandate reverses in cybersecurity (S7) | the judges label nearly every cybersecurity failure `update failed`; in 212 of 216 baseline and 376 of 403 mandate failures both write attempts at the change-set block are rejected as invalid output (attempt logs) | the rejected updates are observed; what the writer took the change set's authority to be is not | described: the line makes the rejected update at that block about twice as frequent; the reading that a rule about authority does not reach an unwritten update is marked provisional | the same runs with the write failure removed (a larger memory capacity, or a patch path that replaces the whole list), with and without the line: if the reversal goes away, the reading holds |
| The mandate does not recover the closed-loop utility loss (S7) | round 3 authorized use 59% without the line, 62% with it, canonical seed, paper's writers | as observed | "the line does not recover it"; what causes the loss is not shown | an account of which real records are deactivated at which write-back lines, and a control that changes what the writer believes about authority without changing what it writes |

""" + s[j:]
rep("**Open checks before the paper.** A human reading of a sample of judged rows (fifty, stratified by label and domain) to validate the labels, since Section 6 and the mechanism half of Section 7 rest on them;",
    "**Open checks before the paper.** A person's reading of the prepared fifty-item sample (`results/diagnosis/human_check/`), since Section 6 and the mechanism half of Section 7 rest on the labels;")

# ---- Section 4: what is matched and what is not
rep("so the stale-restatement comparison changes one thing at a time; this holds for all 36 groups.",
    "so the stale-restatement comparison changes one thing at a time; this holds for all 36 groups. The lifecycle and gap comparisons are not matched in the same way: the base history is drawn from a stream seeded by theme, lifecycle, gap and index, so a case with a different lifecycle or gap has different dates, limits, filler and surrounding text, the theme itself rotates with the gap, and only revoke-and-replace histories have an implicit-revocation variant (108 amendment memories against 216 revoke-and-replace). Those two comparisons are observational.")
rep("**Reading.** With everything but the restatements held fixed, the paper's writers form no false permission on any case with zero stale restatements and form them on 15% of the unauthorized requests once two restatements follow the change. Four restatements are not worse than two (10.8% against 15.4%; the intervals overlap), so at these levels the count of restatements does not add to the effect of their presence. Amendments launder about four times more than clean revoke-and-replace histories (17.3% against 4.5%), and the gap between the grant and its change makes no difference at one to three blocks. Both added writers show the same shape:",
    "**Reading.** With everything but the restatements held fixed, the paper's writers form no false permission on any case with zero stale restatements and form them on 15% of the unauthorized requests once two restatements follow the change. Four restatements are not measurably worse than two (10.8% against 15.4%; the intervals overlap); the data do not separate the two levels and do not show them equal. Two further differences appear on the same corpus and are observed, not matched: histories that amend the grant in place fail about four times as often as histories that revoke and replace it (17.3% against 4.5%), and the failure rate shows no trend across gaps of one to three blocks (9.9, 8.6, 7.7%, all intervals overlapping). Because a change of lifecycle or gap also redraws the case's dates, limits and surrounding text, neither difference is attributed to the lifecycle or the gap alone. Both added writers show the same shape:")
rep("**Takeaway.** On this corpus the trigger is a later message that restates the old permission after it was changed: none of the 324 zero-restatement cases formed a false permission, and two restatements produced as much laundering as four. Histories that amend a grant in place laundered about four times more than histories that revoked and replaced it.",
    "**Takeaway.** On this corpus the trigger is a later message that restates the old permission after it was changed: none of the 324 zero-restatement cases formed a false permission, two restatements were enough, and four were not measurably different from two. Histories that amend a grant in place failed about four times as often as histories that revoked and replaced it, an observed difference between histories that were not otherwise matched.")

# ---- Section 6: counts by update; takeaway provisional
rep("**Result.** Every failure in every run of this note, by where it enters and the judges' majority label. In the closed-loop groups, failures in the shared history blocks are counted once per base memory; failures in write-back blocks belong to one arm; records born from the agent's own lines are the records Section 3 counts.",
    "**Result.** Every failure in every run of this note, by where it enters and the judges' majority label. Each table gives the distinct memory updates behind the rows (one update can authorize several requests, or mint more than one record), the affected requests, and the records; the label columns count rows. In the closed-loop groups, failures in the shared history blocks are counted once per base memory; failures in write-back blocks belong to one arm; records born from the agent's own lines are the records Section 3 counts.")
if S6 is not None:
    tables = S6.read_text(encoding="utf-8").replace("\r\n", "\n").strip("\n")
    a = s.index("*open loop, procurement memory grid (paper's three seeds; all five writers)*")
    b = s.index("**Reading.** Three causes account for")
    s = s[:a] + tables + "\n\n" + s[b:]
rep("**Reading.** Three causes account for nearly all 2,250 failures, and they separate by setting and domain rather than by writer.",
    "**Reading.** Three causes account for nearly all 2,250 judged rows (874 distinct memory updates: 458 labeled restatement applied, 187 update failed, 185 own action as approval, 35 authoritative change misapplied), and they separate by setting and domain rather than by writer.")
rep("The first two are what a rule about authority can address, and Section 7 shows it does; the third is not.",
    "Section 7 tests one rule about authority against all three: it removes most of the first two and makes the third more frequent. That the rule cannot reach an update that is never written is the reading the labels suggest, not something these runs establish, and the labels have not yet been checked by a person.")

# ---- Section 7: provisional mechanism
rep("If it does not, the failure is not about knowing the rule.", "If it does not, stating the rule is not what the failure needs.")
rep("In the closed loop, records minted from the agent's own actions all but disappear (91 to 4), but authorized use at round 3 is unchanged (59% without, 62% with), so the utility loss of Section 3 is not caused by the writer believing the wrong messages.",
    "In the closed loop, records minted from the agent's own actions all but disappear (91 to 4), but authorized use at round 3 is unchanged (59% without, 62% with): the line does not recover the utility loss of Section 3. What causes that loss is not shown here; Section 3 observes real grants being deactivated as the agent's lines arrive, and the line does not stop it.")
rep("The judges say why: cybersecurity's failure was never about authority. The writer knows the duty officer's change set is the authoritative one; it fails to write the replacement, and with the extra instruction it fails more often. A rule about whose word counts cannot fix an update that is never applied.",
    "The judged failures say where, not yet why: nearly all of them, with or without the line, sit at the block carrying the duty officer's signed change set, and in most of them both write attempts are rejected as invalid output (212 of 216 baseline failures, 376 of 403 with the line), so the old permission stays active. The line makes those rejected updates about twice as frequent. Why it does is not established by these runs: the attempt logs show the rejected writes, not what the writer took the change set's authority to be. One reading consistent with the labels is that a rule about whose word counts does not reach a failure where the update is never written; the same runs with the write failure removed (a larger memory capacity, or a patch path that replaces the whole list), with and without the line, would test it.")
rep("**Takeaway.** The one-line mandate is a real mitigation where laundering comes from misread messages, and a harmful one where the failure is the writer's inability to apply a large legitimate change. Before adding such a line, a deployer needs Section 6's answer to which failure they have.",
    "**Takeaway.** The one-line mandate lowers unauthorized submission in procurement and finance at no measured cost in authorized use, and raises it in cybersecurity, where the judged failures are rejected updates at the change-set block rather than misread messages. Before adding such a line, a deployer needs Section 6's answer to which failure they have. Why the line makes the cybersecurity failure more frequent is left open.")

# ---- appendix: stale GLM 5.3 executor entries
rep("- **GLM 5.3 as an executor.** Its executor controls baseline (the paper's prerequisite) is complete in all three domains (792, 576, and 288 trials, passed). Executor runs on the writers' memories (the same frozen memories answered by GPT-OSS, DeepSeek V4 Pro, and GLM 5.3 in one run, Baseten writers only) are prepared in `run_overnight_seq.sh` and deferred.",
    "- **GLM 5.3 as an executor on the closed loop, the pressure route, and the paper's five writers' paper route.** It is the third executor on every open-loop study (Section 5); its executor controls baseline passed in all three domains (792, 576, and 288 trials). The closed loop is not replayed because the executor's actions are written back, so a new executor means new chains; the pressure route inherits the executor of its writer source; the paper's five writers' paper-route memories are not in this clone.")
rep("- **Executors other than GPT-OSS and DeepSeek V4 Pro on the closed loop.** The two-arm closed loop uses the paper's two executors; a third executor there waits on the GLM 5.3 executor runs above.\n", "")

DOC.write_text(s, encoding="utf-8", newline="\n")
print("doc adjusted")
